-- PostgreSQL Schema for Zones
-- This file contains the DDL statements to create the required tables

-- ============================================
-- ZONES TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS zones (
    id VARCHAR(36) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(100),
    description TEXT,
    status VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    heights JSONB,
    geohashes JSONB,
    rectangle JSONB,
    PRIMARY KEY (id, file_name),
    CONSTRAINT zones_file_name_id_unique UNIQUE (file_name, id)
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_zones_file_name ON zones(file_name);
CREATE INDEX IF NOT EXISTS idx_zones_type ON zones(type);
CREATE INDEX IF NOT EXISTS idx_zones_status ON zones(status);
CREATE INDEX IF NOT EXISTS idx_zones_created_at ON zones(created_at);

-- GIN indexes for JSONB columns to enable efficient JSON queries
CREATE INDEX IF NOT EXISTS idx_zones_heights_gin ON zones USING GIN (heights);
CREATE INDEX IF NOT EXISTS idx_zones_geohashes_gin ON zones USING GIN (geohashes);
CREATE INDEX IF NOT EXISTS idx_zones_rectangle_gin ON zones USING GIN (rectangle);

-- ============================================
-- DRONE TELEMETRY TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS drone_telemetry (
    "time" timestamp without time zone NOT NULL,
    drone_id VARCHAR(50) NOT NULL,
    host VARCHAR(255),
    id VARCHAR(36) NOT NULL,
    topic VARCHAR(255),
    alt double precision,
    band_5g VARCHAR(50),
    band_lte VARCHAR(50),
    dlbw_mhz_lte double precision,
    earfcn_5g double precision,
    earfcn_lte double precision,
    gps_fix boolean,
    lat double precision,
    lon double precision,
    mccmnc_lte VARCHAR(50),
    op_mode_lte VARCHAR(50),
    pcell_id_5g VARCHAR(50),
    pcell_id_lte VARCHAR(50),
    rat_5g VARCHAR(50),
    rat_lte VARCHAR(50),
    rsrp_dbm_5g double precision,
    rsrp_dbm_lte double precision,
    rsrq_db_5g double precision,
    rsrq_db_lte double precision,
    rssi_dbm_lte double precision,
    rssnr_db_5g double precision,
    rssnr_db_lte double precision,
    satellites double precision,
    scell_id_lte VARCHAR(50),
    session_id VARCHAR(100) NOT NULL,
    speed_kmh double precision,
    tac_lte VARCHAR(50),
    ulbw_mhz_lte double precision,
    PRIMARY KEY (id),
    CONSTRAINT drone_telemetry_id_unique UNIQUE (id)
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_drone_telemetry_drone_id ON drone_telemetry(drone_id);
CREATE INDEX IF NOT EXISTS idx_drone_telemetry_time ON drone_telemetry("time");
CREATE INDEX IF NOT EXISTS idx_drone_telemetry_location ON drone_telemetry(lat, lon);
CREATE INDEX IF NOT EXISTS idx_drone_telemetry_session_id ON drone_telemetry(session_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_drone_telemetry_id ON drone_telemetry(id);

-- ============================================
-- COMMENTS FOR DOCUMENTATION
-- ============================================
COMMENT ON TABLE zones IS 'Stores zone information with JSONB fields for complex data types';

COMMENT ON COLUMN zones.id IS 'Unique identifier for the zone (UUID format)';
COMMENT ON COLUMN zones.file_name IS 'Name of the file that the zone was created from';
COMMENT ON COLUMN zones.name IS 'Name of the zone';
COMMENT ON COLUMN zones.heights IS 'Array of heights stored as JSONB';
COMMENT ON COLUMN zones.geohashes IS 'Array of geohashes stored as JSONB';
COMMENT ON COLUMN zones.rectangle IS 'Rectangle object stored as JSONB';

COMMENT ON TABLE drone_telemetry IS 'Stores drone telemetry data';

COMMENT ON COLUMN drone_telemetry.id IS 'Unique identifier for the drone telemetry data (UUID format) generated by Telegraf';
COMMENT ON COLUMN drone_telemetry.session_id IS 'Session identifier for grouping telemetry data';
COMMENT ON COLUMN drone_telemetry.drone_id IS 'Identifier for the drone';
COMMENT ON COLUMN drone_telemetry.time IS 'Timestamp of the telemetry data';
COMMENT ON COLUMN drone_telemetry.host IS 'Host of the telemetry data';
COMMENT ON COLUMN drone_telemetry.topic IS 'Topic of the telemetry data';