# === Spring Dev Tools ===
spring.devtools.livereload.enabled=true

# === gRPC Host Configuration ===
app.grpc.host.name=${APP_GRPC_HOST_NAME:localhost}
app.grpc.host.port=${APP_GRPC_HOST_PORT:50051}

logging.level.com.zaxxer.hikari=INFO

# === Working Directories ===
app.file.cache.directory=${EXTREMEXP_OUTPUT_DIR}
app.working.directory.mlflow=/opt/data/xtreme/mlflow/mlartifacts/
app.working.directory=${EXTREMEXP_OUTPUT_DIR}

# === Mock ML Evaluation Path (used for testing) ===
app.mock.ml-evaluation.path-template=/data/xtreme/mlflow/mlartifacts/{experimentId}/{runId}/artifacts/explainability/
# app.mock.ml-evaluation.path=/data/xtreme/mlflow/mlartifacts/359083425157694092/b686b1cd4b96412781cf995349d3c0b9/artifacts/explainability/

# === Real ML Evaluation Path (used in production) ===
app.real.ml-evaluation.path=${EXTREMEXP_OUTPUT_DIR}

# === MLflow Artifact Store ===
app.mlflow.artifacts.root=/opt/data/xtreme/mlflow/mlartifacts
ml.analysis.root=/opt/data/xtreme/mlflow/mlartifacts


# === File Cache Configuration ===
app.file.cache.directory=${EXTREMEXP_OUTPUT_DIR}
app.file.cache.duration=7
# Options: MILLISECONDS, SECONDS, MINUTES, HOURS, DAYS
app.file.cache.unit=DAYS
app.file.cache.size=10GB


# === Experiment Execution Engine ===
# experiment.engine=extremeXP
experiment.engine=mlflow

# === MLflow Tracking Server ===
mlflow.tracking.url=http://localhost:5000
mlflow.tracking.token=test_token

# === Swagger / OpenAPI Configuration ===
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true

# === Optional: File Upload Limits ===
# spring.servlet.multipart.max-file-size=100MB
# spring.servlet.multipart.max-request-size=100MB

# === Optional: DataSource Repository Configuration ===
# app.dataSource.directory=${user.home}/datasources

# to be changed to the actual Kubeflow Pipelines API URL when available
kubeflow.pipelines.base-url=http://localhost:8888

mlflow.execution.engine=kubeflow

observability.service=langfuse

# === Langfuse Configuration ===
langfuse.api.url=http://localhost:3000
langfuse.api.publicKey=${LANGFUSE_PUBLIC_KEY}
langfuse.api.secretKey=${LANGFUSE_SECRET_KEY}