# Use Python image as the base
FROM python:3.10-slim AS builder_grpc
# Set the working directory in the container
WORKDIR /app

# Copy the project source
COPY src ./src

COPY --from=xtremexp-vis-api-xai-grpc-server /app/xai_service.proto ./src/main/proto

# Generate Java classes from the .proto file
RUN apt-get update && \
    apt-get install --no-install-recommends --assume-yes \
      protobuf-compiler

RUN protoc --java_out=./src/main/java ./src/main/proto/xai_service.proto 

# Use Maven image to build the project
# FROM maven:3.8.3-openjdk-17 AS builder
FROM eclipse-temurin:17-jdk-focal AS builder

WORKDIR /app

# Copy the Maven project file
COPY .mvn/ .mvn
COPY mvnw pom.xml ./

# Download dependencies and build the project
RUN ./mvnw dependency:go-offline

# Copy the project source
COPY --from=builder_grpc /app/src ./src

# Package the application
# RUN mvn clean install -DskipTests

# Use OpenJDK 17 as the base image
FROM openjdk:17 AS final

# Set the working directory in the container
WORKDIR /app

# Copy the compiled JAR file from the Maven builder stage
#COPY --from=builder /app/target/xtremexp-vis-api-1.0.0.jar /app

# Copy src files from the builder
COPY --from=builder /app/.mvn .mvn
COPY --from=builder /app/src ./src
COPY --from=builder /app/mvnw ./mvnw
COPY --from=builder /app/pom.xml ./

# Expose the port your Spring Boot app runs on
EXPOSE 8080

# Define the command to run your Spring Boot application
CMD ["./mvnw", "spring-boot:run"]
# ENTRYPOINT ["java", "-jar", "/app/xtremexp-vis-api-1.0.0.jar"]
# ENTRYPOINT ["tail", "-f", "/dev/null"]