package gr.imsi.athenarc.xtremexpvisapi.service;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.locationtech.jts.io.ParseException;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.dao.DataAccessException;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

import gr.imsi.athenarc.xtremexpvisapi.domain.queryV2.params.Zone;
import gr.imsi.athenarc.xtremexpvisapi.repository.ZoneRepository;
import org.geojson.Feature;

@ExtendWith(MockitoExtension.class)
class ZoneServiceTest {

    @Mock
    private ZoneRepository zoneRepository;

    private ZoneService zoneService;

    @BeforeEach
    void setUp() {
        zoneService = new ZoneService(zoneRepository);
    }

    @Test
    void testSaveZoneWithAutoGeneratedId() throws JsonProcessingException, DataAccessException, ParseException {
        // Arrange
        Zone zone = new Zone();
        zone.setFileName("test.csv");
        zone.setName("Test Zone");
        zone.setType("test");
        zone.setDescription("Test description");
        zone.setStatus("active");
        
        // Mock repository behavior
        when(zoneRepository.save(any(Zone.class))).thenAnswer(invocation -> invocation.getArgument(0));
        
        // Act
        Zone savedZone = zoneService.save(zone);
        
        // Assert
        assertNotNull(savedZone.getId());
        assertDoesNotThrow(() -> UUID.fromString(savedZone.getId()));
        assertEquals("test.csv", savedZone.getFileName());
        assertEquals("Test Zone", savedZone.getName());
        assertEquals("test", savedZone.getType());
        assertEquals("Test description", savedZone.getDescription());
        assertEquals("active", savedZone.getStatus());
        assertNotNull(savedZone.getCreatedAt());
        
        // Verify repository was called
        verify(zoneRepository).save(savedZone);
    }

    @Test
    void testSaveZoneWithProvidedId() throws JsonProcessingException, DataAccessException, ParseException {
        // Arrange
        Zone zone = new Zone();
        zone.setId("existing-zone-123");
        zone.setFileName("test.csv");
        zone.setName("Test Zone");
        
        // Mock repository behavior
        when(zoneRepository.save(any(Zone.class))).thenAnswer(invocation -> invocation.getArgument(0));
        
        // Act
        Zone savedZone = zoneService.save(zone);
        
        // Assert
        assertEquals("existing-zone-123", savedZone.getId());
        assertEquals("test.csv", savedZone.getFileName());
        assertEquals("Test Zone", savedZone.getName());
        
        // Verify repository was called
        verify(zoneRepository).save(savedZone);
        // Should not call findAll() when ID is provided
        verify(zoneRepository, never()).findAll();
    }

    @Test
    void testSaveZoneWithMissingRequiredFields() throws JsonProcessingException, DataAccessException, ParseException {
        // Arrange
        Zone zone = new Zone();
        zone.setFileName("test.csv");
        // Missing name field
        
        // Act & Assert
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
            zoneService.save(zone);
        });
        
        assertEquals("Zone name is required", exception.getMessage());
        
        // Verify repository was not called
        verify(zoneRepository, never()).save(any());
    }

    @Test
    void testSaveZoneWithMissingFileName() throws JsonProcessingException, DataAccessException, ParseException {
        // Arrange
        Zone zone = new Zone();
        zone.setName("Test Zone");
        // Missing fileName field
        
        // Act & Assert
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
            zoneService.save(zone);
        });
        
        assertEquals("Zone fileName is required", exception.getMessage());
        
        // Verify repository was not called
        verify(zoneRepository, never()).save(any());
    }

    @Test
    void testSaveZoneWithNullZone() throws JsonProcessingException, DataAccessException, ParseException {
        // Act & Assert
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
            zoneService.save(null);
        });
        
        assertEquals("Zone cannot be null", exception.getMessage());
        
        // Verify repository was not called
        verify(zoneRepository, never()).save(any());
    }

    @Test
    void testSaveZoneWithEmptyId() throws JsonProcessingException, DataAccessException, ParseException {
        // Arrange
        Zone zone = new Zone();
        zone.setId(""); // Empty ID
        zone.setFileName("test.csv");
        zone.setName("Test Zone");
        
        // Mock repository behavior
        when(zoneRepository.save(any(Zone.class))).thenAnswer(invocation -> invocation.getArgument(0));
        
        // Act
        Zone savedZone = zoneService.save(zone);
        
        // Assert
        assertNotNull(savedZone.getId());
        assertDoesNotThrow(() -> UUID.fromString(savedZone.getId()));
        assertFalse(savedZone.getId().isEmpty());
        
        // Verify repository was called
        verify(zoneRepository).save(savedZone);
    }

    @Test
    void testSaveZoneWithWhitespaceId() throws JsonProcessingException, DataAccessException, ParseException {
        // Arrange
        Zone zone = new Zone();
        zone.setId("   "); // Whitespace ID
        zone.setFileName("test.csv");
        zone.setName("Test Zone");
        
        // Mock repository behavior
        when(zoneRepository.save(any(Zone.class))).thenAnswer(invocation -> invocation.getArgument(0));
        
        // Act
        Zone savedZone = zoneService.save(zone);
        
        // Assert
        assertNotNull(savedZone.getId());
        assertDoesNotThrow(() -> UUID.fromString(savedZone.getId()));
        assertFalse(savedZone.getId().trim().isEmpty());
        
        // Verify repository was called
        verify(zoneRepository).save(savedZone);
    }

    @Test
    void testSaveZoneWithProvidedIdStillWorks() throws JsonProcessingException, DataAccessException, ParseException {
        // Arrange
        Zone zone = new Zone();
        zone.setId("existing-zone-123");
        zone.setFileName("test.csv");
        zone.setName("Test Zone");
        
        // Mock repository behavior
        when(zoneRepository.save(any(Zone.class))).thenAnswer(invocation -> invocation.getArgument(0));
        
        // Act
        Zone savedZone = zoneService.save(zone);
        
        // Assert
        assertEquals("existing-zone-123", savedZone.getId());
        assertEquals("test.csv", savedZone.getFileName());
        assertEquals("Test Zone", savedZone.getName());
        
        // Verify repository was called
        verify(zoneRepository).save(zone);
        // Should not call findAll() when ID is provided
        verify(zoneRepository, never()).findAll();
    }

    @Test
    void testUpdateZoneSuccessfully() throws JsonProcessingException, DataAccessException, ParseException {
        // Arrange
        Zone zone = new Zone();
        zone.setId("existing-zone-123");
        zone.setFileName("test.csv");
        zone.setName("Updated Zone Name");
        zone.setType("updated");
        zone.setStatus("inactive");
        zone.setDescription("Updated description");
        
        // Mock repository behavior
        when(zoneRepository.save(any(Zone.class))).thenAnswer(invocation -> invocation.getArgument(0));
        
        // Act
        Zone savedZone = zoneService.save(zone);
        
        // Assert
        assertEquals("existing-zone-123", savedZone.getId());
        assertEquals("test.csv", savedZone.getFileName());
        assertEquals("Updated Zone Name", savedZone.getName());
        assertEquals("updated", savedZone.getType());
        assertEquals("inactive", savedZone.getStatus());
        assertEquals("Updated description", savedZone.getDescription());
        
        // Verify repository was called
        verify(zoneRepository).save(zone);
        // Should not call findAll() when ID is provided
        verify(zoneRepository, never()).findAll();
    }

    @Test
    void testUpdateZoneWithNullId() throws JsonProcessingException, DataAccessException, ParseException {
        // Arrange
        Zone zone = new Zone();
        zone.setId(null); // No ID provided
        zone.setFileName("test.csv");
        zone.setName("New Zone Name");
        
        // Mock repository behavior for ID generation
        when(zoneRepository.save(any(Zone.class))).thenAnswer(invocation -> invocation.getArgument(0));
        
        // Act
        Zone savedZone = zoneService.save(zone);
        
        // Assert
        assertNotNull(savedZone.getId());
        assertDoesNotThrow(() -> UUID.fromString(savedZone.getId()));
        assertEquals("test.csv", savedZone.getFileName());
        assertEquals("New Zone Name", savedZone.getName());
        
        // Verify repository was called for ID generation and saving
        verify(zoneRepository).save(savedZone);
    }

    @Test
    void testUpdateZoneWithEmptyId() throws JsonProcessingException, DataAccessException, ParseException {
        // Arrange
        Zone zone = new Zone();
        zone.setId(""); // Empty ID
        zone.setFileName("test.csv");
        zone.setName("New Zone Name");
        
        // Mock repository behavior for ID generation
        when(zoneRepository.save(any(Zone.class))).thenAnswer(invocation -> invocation.getArgument(0));
        
        // Act
        Zone savedZone = zoneService.save(zone);
        
        // Assert
        assertNotNull(savedZone.getId());
        assertDoesNotThrow(() -> UUID.fromString(savedZone.getId()));
        assertEquals("test.csv", savedZone.getFileName());
        assertEquals("New Zone Name", savedZone.getName());
        
        // Verify repository was called for ID generation and saving
        verify(zoneRepository).save(savedZone);
    }

    @Test
    void testUpdateZoneWithWhitespaceId() throws JsonProcessingException, DataAccessException, ParseException {
        // Arrange
        Zone zone = new Zone();
        zone.setId("   "); // Whitespace ID
        zone.setFileName("test.csv");
        zone.setName("New Zone Name");
        
        // Mock repository behavior for ID generation
        when(zoneRepository.save(any(Zone.class))).thenAnswer(invocation -> invocation.getArgument(0));
        
        // Act
        Zone savedZone = zoneService.save(zone);
        
        // Assert
        assertNotNull(savedZone.getId());
        assertDoesNotThrow(() -> UUID.fromString(savedZone.getId()));
        assertEquals("test.csv", savedZone.getFileName());
        assertEquals("New Zone Name", savedZone.getName());
        
        // Verify repository was called for ID generation and saving
        verify(zoneRepository).save(savedZone);
    }

    @Test
    void testUpdateZoneWithExistingIdConflict() throws JsonProcessingException, DataAccessException, ParseException {
        // Arrange
        Zone zone = new Zone();
        zone.setId("existing-zone-123");
        zone.setFileName("test.csv");
        zone.setName("Updated Zone Name");
        
        // Mock repository behavior
        when(zoneRepository.save(any(Zone.class))).thenAnswer(invocation -> invocation.getArgument(0));
        
        // Act
        Zone savedZone = zoneService.save(zone);
        
        // Assert
        assertEquals("existing-zone-123", savedZone.getId());
        assertEquals("test.csv", savedZone.getFileName());
        assertEquals("Updated Zone Name", savedZone.getName());
        
        // Verify repository was called
        verify(zoneRepository).save(zone);
        // Should not call findAll() when ID is provided
        verify(zoneRepository, never()).findAll();
    }

    @Test
    void testUpdateZonePreservesExistingData() throws JsonProcessingException, DataAccessException, ParseException {
        // Arrange
        Zone zone = new Zone();
        zone.setId("existing-zone-123");
        zone.setFileName("test.csv");
        zone.setName("Updated Zone Name");
        // Only updating name, other fields should remain unchanged
        
        // Mock repository behavior
        when(zoneRepository.save(any(Zone.class))).thenAnswer(invocation -> invocation.getArgument(0));
        
        // Act
        Zone savedZone = zoneService.save(zone);
        
        // Assert
        assertEquals("existing-zone-123", savedZone.getId());
        assertEquals("test.csv", savedZone.getFileName());
        assertEquals("Updated Zone Name", savedZone.getName());
        // Other fields should have default values set by setDefaultValues()
        assertEquals("active", savedZone.getStatus());
        assertEquals("general", savedZone.getType());
        assertNotNull(savedZone.getCreatedAt());
        
        // Verify repository was called
        verify(zoneRepository).save(zone);
        verify(zoneRepository, never()).findAll();
    }

    @Test
    void testUpdateZoneWithAllFields() throws JsonProcessingException, DataAccessException, ParseException {
        // Arrange
        Zone zone = new Zone();
        zone.setId("existing-zone-123");
        zone.setFileName("test.csv");
        zone.setName("Fully Updated Zone");
        zone.setType("commercial");
        zone.setStatus("active");
        zone.setDescription("Complete zone update");
        zone.setCreatedAt("2024-01-15T10:30:00");
        
        // Mock repository behavior
        when(zoneRepository.save(any(Zone.class))).thenAnswer(invocation -> invocation.getArgument(0));
        
        // Act
        Zone savedZone = zoneService.save(zone);
        
        // Assert
        assertEquals("existing-zone-123", savedZone.getId());
        assertEquals("test.csv", savedZone.getFileName());
        assertEquals("Fully Updated Zone", savedZone.getName());
        assertEquals("commercial", savedZone.getType());
        assertEquals("active", savedZone.getStatus());
        assertEquals("Complete zone update", savedZone.getDescription());
        assertEquals("2024-01-15T10:30:00", savedZone.getCreatedAt());
        
        // Verify repository was called
        verify(zoneRepository).save(zone);
        verify(zoneRepository, never()).findAll();
    }

    @Test
    void testUpdateZoneRepositoryFailure() throws JsonProcessingException, DataAccessException, ParseException {
        // Arrange
        Zone zone = new Zone();
        zone.setId("existing-zone-123");
        zone.setFileName("test.csv");
        zone.setName("Updated Zone Name");
        
        // Mock repository to throw exception
        when(zoneRepository.save(any(Zone.class))).thenThrow(new RuntimeException("Database error"));
        
        // Act & Assert
        RuntimeException exception = assertThrows(RuntimeException.class, () -> {
            zoneService.save(zone);
        });
        
        assertEquals("Failed to save zone", exception.getMessage());
        
        // Verify repository was called
        verify(zoneRepository).save(zone);
        verify(zoneRepository, never()).findAll();
    }

    @Test
    void testSaveZoneWithRectangle() throws JsonProcessingException, DataAccessException, ParseException {
        // Arrange
        Zone zone = new Zone();
        zone.setFileName("test.csv");
        zone.setName("Zone with Rectangle");
        
        // Note: Rectangle uses Range<Float> for lon/lat, so we'll test with a simple case
        zone.setFeature(pointFeature(0.0, 0.0));
        
        // Mock repository behavior
        when(zoneRepository.save(any(Zone.class))).thenAnswer(invocation -> invocation.getArgument(0));
        
        // Act
        Zone savedZone = zoneService.save(zone);
        
        // Assert
        assertNotNull(savedZone.getId());
        assertDoesNotThrow(() -> UUID.fromString(savedZone.getId()));
        assertNotNull(savedZone.getFeature());
        assertNotNull(savedZone.getFeature().getGeometry());
        
        // Verify repository was called
        verify(zoneRepository).save(savedZone);
    }

    @Test
    void testSaveZoneWithHeights() throws JsonProcessingException, DataAccessException, ParseException {
        // Arrange
        Zone zone = new Zone();
        zone.setFileName("test.csv");
        zone.setName("Zone with Heights");
        
        Double[] heights = {100.0, 150.0, 200.0, 175.0};
        zone.setHeights(heights);
        
        // Mock repository behavior
        when(zoneRepository.save(any(Zone.class))).thenAnswer(invocation -> invocation.getArgument(0));
        
        // Act
        Zone savedZone = zoneService.save(zone);
        
        // Assert
        assertNotNull(savedZone.getId());
        assertDoesNotThrow(() -> UUID.fromString(savedZone.getId()));
        assertNotNull(savedZone.getHeights());
        assertEquals(4, savedZone.getHeights().length);
        assertEquals(100.0, savedZone.getHeights()[0]);
        assertEquals(150.0, savedZone.getHeights()[1]);
        assertEquals(200.0, savedZone.getHeights()[2]);
        assertEquals(175.0, savedZone.getHeights()[3]);
        
        // Verify repository was called
        verify(zoneRepository).save(savedZone);
    }

    @Test
    void testSaveZoneWithCompleteData() throws JsonProcessingException, DataAccessException, ParseException {
        // Arrange
        Zone zone = new Zone();
        zone.setFileName("complete.csv");
        zone.setName("Complete Zone");
        zone.setType("commercial");
        zone.setStatus("active");
        zone.setDescription("A complete zone with all fields");
        zone.setFeature(pointFeature(0.0, 0.0));
        
        Double[] heights = {50.0, 75.0, 100.0};
        zone.setHeights(heights);
        
        // Mock repository behavior
        when(zoneRepository.save(any(Zone.class))).thenAnswer(invocation -> invocation.getArgument(0));
        
        // Act
        Zone savedZone = zoneService.save(zone);
        
        // Assert
        assertNotNull(savedZone.getId());
        assertDoesNotThrow(() -> UUID.fromString(savedZone.getId()));
        assertEquals("complete.csv", savedZone.getFileName());
        assertEquals("Complete Zone", savedZone.getName());
        assertEquals("commercial", savedZone.getType());
        assertEquals("active", savedZone.getStatus());
        assertEquals("A complete zone with all fields", savedZone.getDescription());
        assertNotNull(savedZone.getCreatedAt());
        assertNotNull(savedZone.getFeature());
        assertNotNull(savedZone.getFeature().getGeometry());
        assertNotNull(savedZone.getHeights());
        assertEquals(3, savedZone.getHeights().length);
        
        // Verify repository was called
        verify(zoneRepository).save(savedZone);
    }

    @Test
    void testFindAllSuccessfully() {
        // Arrange
        Zone zone1 = new Zone();
        zone1.setId("zone_1");
        zone1.setFileName("test1.csv");
        zone1.setName("Zone 1");
        
        Zone zone2 = new Zone();
        zone2.setId("zone_2");
        zone2.setFileName("test2.csv");
        zone2.setName("Zone 2");
        
        List<Zone> expectedZones = Arrays.asList(zone1, zone2);
        when(zoneRepository.findAll()).thenReturn(expectedZones);
        
        // Act
        List<Zone> actualZones = zoneService.findAll();
        
        // Assert
        assertNotNull(actualZones);
        assertEquals(2, actualZones.size());
        assertEquals("zone_1", actualZones.get(0).getId());
        assertEquals("zone_2", actualZones.get(1).getId());
        
        // Verify repository was called
        verify(zoneRepository).findAll();
    }

    @Test
    void testFindAllRepositoryFailure() {
        // Arrange
        when(zoneRepository.findAll()).thenThrow(new RuntimeException("Database error"));
        
        // Act & Assert
        RuntimeException exception = assertThrows(RuntimeException.class, () -> {
            zoneService.findAll();
        });
        
        assertEquals("Failed to retrieve all zones", exception.getMessage());
        
        // Verify repository was called
        verify(zoneRepository).findAll();
    }

    @Test
    void testFindByFileNameSuccessfully() {
        // Arrange
        String fileName = "test.csv";
        Zone zone1 = new Zone();
        zone1.setId("zone_1");
        zone1.setFileName(fileName);
        zone1.setName("Zone 1");
        
        Zone zone2 = new Zone();
        zone2.setId("zone_2");
        zone2.setFileName(fileName);
        zone2.setName("Zone 2");
        
        List<Zone> expectedZones = Arrays.asList(zone1, zone2);
        when(zoneRepository.findByFileName(fileName)).thenReturn(expectedZones);
        
        // Act
        List<Zone> actualZones = zoneService.findByFileName(fileName);
        
        // Assert
        assertNotNull(actualZones);
        assertEquals(2, actualZones.size());
        assertEquals(fileName, actualZones.get(0).getFileName());
        assertEquals(fileName, actualZones.get(1).getFileName());
        
        // Verify repository was called
        verify(zoneRepository).findByFileName(fileName);
    }

    @Test
    void testFindByFileNameWithEmptyFileName() {
        // Arrange
        String fileName = "";
        
        // Act & Assert
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
            zoneService.findByFileName(fileName);
        });
        
        assertEquals("FileName cannot be null or empty", exception.getMessage());
        
        // Verify repository was NOT called
        verify(zoneRepository, never()).findByFileName(any());
    }

    @Test
    void testFindByFileNameRepositoryFailure() {
        // Arrange
        String fileName = "test.csv";
        when(zoneRepository.findByFileName(fileName)).thenThrow(new RuntimeException("Database error"));
        
        // Act & Assert
        RuntimeException exception = assertThrows(RuntimeException.class, () -> {
            zoneService.findByFileName(fileName);
        });
        
        assertEquals("Failed to find zones by fileName: " + fileName, exception.getMessage());
        
        // Verify repository was called
        verify(zoneRepository).findByFileName(fileName);
    }

    @Test
    void testFindByTypeSuccessfully() {
        // Arrange
        String type = "commercial";
        Zone zone1 = new Zone();
        zone1.setId("zone_1");
        zone1.setFileName("test1.csv");
        zone1.setName("Commercial Zone 1");
        zone1.setType(type);
        
        Zone zone2 = new Zone();
        zone2.setId("zone_2");
        zone2.setFileName("test2.csv");
        zone2.setName("Commercial Zone 2");
        zone2.setType(type);
        
        List<Zone> expectedZones = Arrays.asList(zone1, zone2);
        when(zoneRepository.findByType(type)).thenReturn(expectedZones);
        
        // Act
        List<Zone> actualZones = zoneService.findByType(type);
        
        // Assert
        assertNotNull(actualZones);
        assertEquals(2, actualZones.size());
        assertEquals(type, actualZones.get(0).getType());
        assertEquals(type, actualZones.get(1).getType());
        
        // Verify repository was called
        verify(zoneRepository).findByType(type);
    }

    @Test
    void testFindByTypeWithEmptyType() {
        // Arrange
        String type = "";
        
        // Act & Assert
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
            zoneService.findByType(type);
        });
        
        assertEquals("Type cannot be null or empty", exception.getMessage());
        
        // Verify repository was NOT called
        verify(zoneRepository, never()).findByType(any());
    }

    @Test
    void testFindByStatusSuccessfully() {
        // Arrange
        String status = "active";
        Zone zone1 = new Zone();
        zone1.setId("zone_1");
        zone1.setFileName("test1.csv");
        zone1.setName("Active Zone 1");
        zone1.setStatus(status);
        
        Zone zone2 = new Zone();
        zone2.setId("zone_2");
        zone2.setFileName("test2.csv");
        zone2.setName("Active Zone 2");
        zone2.setStatus(status);
        
        List<Zone> expectedZones = Arrays.asList(zone1, zone2);
        when(zoneRepository.findByStatus(status)).thenReturn(expectedZones);
        
        // Act
        List<Zone> actualZones = zoneService.findByStatus(status);
        
        // Assert
        assertNotNull(actualZones);
        assertEquals(2, actualZones.size());
        assertEquals(status, actualZones.get(0).getStatus());
        assertEquals(status, actualZones.get(1).getStatus());
        
        // Verify repository was called
        verify(zoneRepository).findByStatus(status);
    }

    @Test
    void testFindByStatusWithEmptyStatus() {
        // Arrange
        String status = "";
        
        // Act & Assert
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
            zoneService.findByStatus(status);
        });
        
        assertEquals("Status cannot be null or empty", exception.getMessage());
        
        // Verify repository was NOT called
        verify(zoneRepository, never()).findByStatus(any());
    }

    @Test
    void testFindByFileNameAndIdSuccessfully() {
        // Arrange
        String fileName = "test.csv";
        String zoneId = "zone_123";
        
        Zone expectedZone = new Zone();
        expectedZone.setId(zoneId);
        expectedZone.setFileName(fileName);
        expectedZone.setName("Test Zone");
        
        when(zoneRepository.findByFileNameAndId(fileName, zoneId)).thenReturn(java.util.Optional.of(expectedZone));
        
        // Act
        java.util.Optional<Zone> actualZone = zoneService.findByFileNameAndId(fileName, zoneId);
        
        // Assert
        assertTrue(actualZone.isPresent());
        assertEquals(zoneId, actualZone.get().getId());
        assertEquals(fileName, actualZone.get().getFileName());
        assertEquals("Test Zone", actualZone.get().getName());
        
        // Verify repository was called
        verify(zoneRepository).findByFileNameAndId(fileName, zoneId);
    }

    @Test
    void testFindByFileNameAndIdNotFound() {
        // Arrange
        String fileName = "test.csv";
        String zoneId = "zone_123";
        
        when(zoneRepository.findByFileNameAndId(fileName, zoneId)).thenReturn(java.util.Optional.empty());
        
        // Act
        java.util.Optional<Zone> actualZone = zoneService.findByFileNameAndId(fileName, zoneId);
        
        // Assert
        assertFalse(actualZone.isPresent());
        
        // Verify repository was called
        verify(zoneRepository).findByFileNameAndId(fileName, zoneId);
    }

    @Test
    void testFindByFileNameAndIdWithEmptyFileName() {
        // Arrange
        String fileName = "";
        String zoneId = "zone_123";
        
        // Act & Assert
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
            zoneService.findByFileNameAndId(fileName, zoneId);
        });
        
        assertEquals("FileName cannot be null or empty", exception.getMessage());
        
        // Verify repository was NOT called
        verify(zoneRepository, never()).findByFileNameAndId(any(), any());
    }

    @Test
    void testFindByFileNameAndIdWithEmptyId() {
        // Arrange
        String fileName = "test.csv";
        String zoneId = "";
        
        // Act & Assert
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
            zoneService.findByFileNameAndId(fileName, zoneId);
        });
        
        assertEquals("Zone id cannot be null or empty", exception.getMessage());
        
        // Verify repository was NOT called
        verify(zoneRepository, never()).findByFileNameAndId(any(), any());
    }

    @Test
    void testDeleteByFileNameAndIdSuccessfully() {
        // Arrange
        String fileName = "test.csv";
        String zoneId = "zone_123";
        
        when(zoneRepository.deleteByFileNameAndId(fileName, zoneId)).thenReturn(true);
        
        // Act
        boolean result = zoneService.deleteByFileNameAndId(fileName, zoneId);
        
        // Assert
        assertTrue(result);
        
        // Verify repository was called
        verify(zoneRepository).deleteByFileNameAndId(fileName, zoneId);
    }

    @Test
    void testDeleteByFileNameAndIdNotFound() {
        // Arrange
        String fileName = "test.csv";
        String zoneId = "zone_123";
        
        when(zoneRepository.deleteByFileNameAndId(fileName, zoneId)).thenReturn(false);
        
        // Act
        boolean result = zoneService.deleteByFileNameAndId(fileName, zoneId);
        
        // Assert
        assertFalse(result);
        
        // Verify repository was called
        verify(zoneRepository).deleteByFileNameAndId(fileName, zoneId);
    }

    @Test
    void testDeleteByFileNameAndIdWithEmptyFileName() {
        // Arrange
        String fileName = "";
        String zoneId = "zone_123";
        
        // Act & Assert
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
            zoneService.deleteByFileNameAndId(fileName, zoneId);
        });
        
        assertEquals("FileName cannot be null or empty", exception.getMessage());
        
        // Verify repository was NOT called
        verify(zoneRepository, never()).deleteByFileNameAndId(any(), any());
    }

    @Test
    void testDeleteByFileNameAndIdWithEmptyId() {
        // Arrange
        String fileName = "test.csv";
        String zoneId = "";
        
        // Act & Assert
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
            zoneService.deleteByFileNameAndId(fileName, zoneId);
        });
        
        assertEquals("Zone id cannot be null or empty", exception.getMessage());
        
        // Verify repository was NOT called
        verify(zoneRepository, never()).deleteByFileNameAndId(any(), any());
    }

    @Test
    void testDeleteByFileNameSuccessfully() {
        // Arrange
        String fileName = "test.csv";
        
        when(zoneRepository.deleteByFileName(fileName)).thenReturn(true);
        
        // Act
        boolean result = zoneService.deleteByFileName(fileName);
        
        // Assert
        assertTrue(result);
        
        // Verify repository was called
        verify(zoneRepository).deleteByFileName(fileName);
    }

    @Test
    void testDeleteByFileNameNotFound() {
        // Arrange
        String fileName = "test.csv";
        
        when(zoneRepository.deleteByFileName(fileName)).thenReturn(false);
        
        // Act
        boolean result = zoneService.deleteByFileName(fileName);
        
        // Assert
        assertFalse(result);
        
        // Verify repository was called
        verify(zoneRepository).deleteByFileName(fileName);
    }

    @Test
    void testDeleteByFileNameWithEmptyFileName() {
        // Arrange
        String fileName = "";
        
        // Act & Assert
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
            zoneService.deleteByFileName(fileName);
        });
        
        assertEquals("FileName cannot be null or empty", exception.getMessage());
        
        // Verify repository was NOT called
        verify(zoneRepository, never()).deleteByFileName(any());
    }

    @Test
    void testExistsByFileNameSuccessfully() {
        // Arrange
        String fileName = "test.csv";
        
        when(zoneRepository.existsByFileName(fileName)).thenReturn(true);
        
        // Act
        boolean result = zoneService.existsByFileName(fileName);
        
        // Assert
        assertTrue(result);
        
        // Verify repository was called
        verify(zoneRepository).existsByFileName(fileName);
    }

    @Test
    void testExistsByFileNameWithEmptyFileName() {
        // Arrange
        String fileName = "";
        
        // Act & Assert
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
            zoneService.existsByFileName(fileName);
        });
        
        assertEquals("FileName cannot be null or empty", exception.getMessage());
        
        // Verify repository was NOT called
        verify(zoneRepository, never()).existsByFileName(any());
    }

    @Test
    void testGetAllFileNamesSuccessfully() {
        // Arrange
        List<String> expectedFileNames = Arrays.asList("test1.csv", "test2.csv", "test3.csv");
        when(zoneRepository.getAllFileNames()).thenReturn(expectedFileNames);
        
        // Act
        List<String> actualFileNames = zoneService.getAllFileNames();
        
        // Assert
        assertNotNull(actualFileNames);
        assertEquals(3, actualFileNames.size());
        assertTrue(actualFileNames.contains("test1.csv"));
        assertTrue(actualFileNames.contains("test2.csv"));
        assertTrue(actualFileNames.contains("test3.csv"));
        
        // Verify repository was called
        verify(zoneRepository).getAllFileNames();
    }

    private static Feature pointFeature(double lon, double lat) {
        try {
            String json = """
                {
                  "type": "Feature",
                  "geometry": { "type": "Point", "coordinates": [%s, %s] },
                  "properties": {}
                }
                """.formatted(lon, lat);
            return new ObjectMapper().readValue(json, Feature.class);
        } catch (Exception e) {
            throw new RuntimeException("Failed to build test GeoJSON Feature", e);
        }
    }
}
