// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xai_service.proto

package gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated;

/**
 * Protobuf type {@code Axis}
 */
public  final class Axis extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Axis)
    AxisOrBuilder {
  // Use Axis.newBuilder() to construct.
  private Axis(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Axis() {
    axisName_ = "";
    axisValues_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    axisType_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Axis(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            axisName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              axisValues_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            axisValues_.add(s);
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            axisType_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        axisValues_ = axisValues_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_Axis_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_Axis_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis.class, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis.Builder.class);
  }

  private int bitField0_;
  public static final int AXIS_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object axisName_;
  /**
   * <code>string axis_name = 1;</code>
   */
  public java.lang.String getAxisName() {
    java.lang.Object ref = axisName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      axisName_ = s;
      return s;
    }
  }
  /**
   * <code>string axis_name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAxisNameBytes() {
    java.lang.Object ref = axisName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      axisName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AXIS_VALUES_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList axisValues_;
  /**
   * <code>repeated string axis_values = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getAxisValuesList() {
    return axisValues_;
  }
  /**
   * <code>repeated string axis_values = 2;</code>
   */
  public int getAxisValuesCount() {
    return axisValues_.size();
  }
  /**
   * <code>repeated string axis_values = 2;</code>
   */
  public java.lang.String getAxisValues(int index) {
    return axisValues_.get(index);
  }
  /**
   * <code>repeated string axis_values = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAxisValuesBytes(int index) {
    return axisValues_.getByteString(index);
  }

  public static final int AXIS_TYPE_FIELD_NUMBER = 3;
  private volatile java.lang.Object axisType_;
  /**
   * <code>string axis_type = 3;</code>
   */
  public java.lang.String getAxisType() {
    java.lang.Object ref = axisType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      axisType_ = s;
      return s;
    }
  }
  /**
   * <code>string axis_type = 3;</code>
   */
  public com.google.protobuf.ByteString
      getAxisTypeBytes() {
    java.lang.Object ref = axisType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      axisType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAxisNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, axisName_);
    }
    for (int i = 0; i < axisValues_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, axisValues_.getRaw(i));
    }
    if (!getAxisTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, axisType_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAxisNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, axisName_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < axisValues_.size(); i++) {
        dataSize += computeStringSizeNoTag(axisValues_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAxisValuesList().size();
    }
    if (!getAxisTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, axisType_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis)) {
      return super.equals(obj);
    }
    gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis other = (gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis) obj;

    boolean result = true;
    result = result && getAxisName()
        .equals(other.getAxisName());
    result = result && getAxisValuesList()
        .equals(other.getAxisValuesList());
    result = result && getAxisType()
        .equals(other.getAxisType());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AXIS_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getAxisName().hashCode();
    if (getAxisValuesCount() > 0) {
      hash = (37 * hash) + AXIS_VALUES_FIELD_NUMBER;
      hash = (53 * hash) + getAxisValuesList().hashCode();
    }
    hash = (37 * hash) + AXIS_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getAxisType().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Axis}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Axis)
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.AxisOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_Axis_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_Axis_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis.class, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis.Builder.class);
    }

    // Construct using gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      axisName_ = "";

      axisValues_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      axisType_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_Axis_descriptor;
    }

    public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis getDefaultInstanceForType() {
      return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis.getDefaultInstance();
    }

    public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis build() {
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis buildPartial() {
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis result = new gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.axisName_ = axisName_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        axisValues_ = axisValues_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.axisValues_ = axisValues_;
      result.axisType_ = axisType_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis) {
        return mergeFrom((gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis other) {
      if (other == gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis.getDefaultInstance()) return this;
      if (!other.getAxisName().isEmpty()) {
        axisName_ = other.axisName_;
        onChanged();
      }
      if (!other.axisValues_.isEmpty()) {
        if (axisValues_.isEmpty()) {
          axisValues_ = other.axisValues_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureAxisValuesIsMutable();
          axisValues_.addAll(other.axisValues_);
        }
        onChanged();
      }
      if (!other.getAxisType().isEmpty()) {
        axisType_ = other.axisType_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object axisName_ = "";
    /**
     * <code>string axis_name = 1;</code>
     */
    public java.lang.String getAxisName() {
      java.lang.Object ref = axisName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        axisName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string axis_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAxisNameBytes() {
      java.lang.Object ref = axisName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        axisName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string axis_name = 1;</code>
     */
    public Builder setAxisName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      axisName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string axis_name = 1;</code>
     */
    public Builder clearAxisName() {
      
      axisName_ = getDefaultInstance().getAxisName();
      onChanged();
      return this;
    }
    /**
     * <code>string axis_name = 1;</code>
     */
    public Builder setAxisNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      axisName_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList axisValues_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureAxisValuesIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        axisValues_ = new com.google.protobuf.LazyStringArrayList(axisValues_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string axis_values = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAxisValuesList() {
      return axisValues_.getUnmodifiableView();
    }
    /**
     * <code>repeated string axis_values = 2;</code>
     */
    public int getAxisValuesCount() {
      return axisValues_.size();
    }
    /**
     * <code>repeated string axis_values = 2;</code>
     */
    public java.lang.String getAxisValues(int index) {
      return axisValues_.get(index);
    }
    /**
     * <code>repeated string axis_values = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAxisValuesBytes(int index) {
      return axisValues_.getByteString(index);
    }
    /**
     * <code>repeated string axis_values = 2;</code>
     */
    public Builder setAxisValues(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAxisValuesIsMutable();
      axisValues_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string axis_values = 2;</code>
     */
    public Builder addAxisValues(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAxisValuesIsMutable();
      axisValues_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string axis_values = 2;</code>
     */
    public Builder addAllAxisValues(
        java.lang.Iterable<java.lang.String> values) {
      ensureAxisValuesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, axisValues_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string axis_values = 2;</code>
     */
    public Builder clearAxisValues() {
      axisValues_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string axis_values = 2;</code>
     */
    public Builder addAxisValuesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureAxisValuesIsMutable();
      axisValues_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object axisType_ = "";
    /**
     * <code>string axis_type = 3;</code>
     */
    public java.lang.String getAxisType() {
      java.lang.Object ref = axisType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        axisType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string axis_type = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAxisTypeBytes() {
      java.lang.Object ref = axisType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        axisType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string axis_type = 3;</code>
     */
    public Builder setAxisType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      axisType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string axis_type = 3;</code>
     */
    public Builder clearAxisType() {
      
      axisType_ = getDefaultInstance().getAxisType();
      onChanged();
      return this;
    }
    /**
     * <code>string axis_type = 3;</code>
     */
    public Builder setAxisTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      axisType_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:Axis)
  }

  // @@protoc_insertion_point(class_scope:Axis)
  private static final gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis();
  }

  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Axis>
      PARSER = new com.google.protobuf.AbstractParser<Axis>() {
    public Axis parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Axis(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Axis> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Axis> getParserForType() {
    return PARSER;
  }

  public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

