// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xai_service.proto

package gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated;

/**
 * Protobuf type {@code ExplanationsRequest}
 */
public  final class ExplanationsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ExplanationsRequest)
    ExplanationsRequestOrBuilder {
  // Use ExplanationsRequest.newBuilder() to construct.
  private ExplanationsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExplanationsRequest() {
    explanationType_ = "";
    explanationMethod_ = "";
    model_ = "";
    feature1_ = "";
    feature2_ = "";
    numInfluential_ = 0;
    proxyDataset_ = com.google.protobuf.ByteString.EMPTY;
    query_ = com.google.protobuf.ByteString.EMPTY;
    features_ = "";
    target_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ExplanationsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            explanationType_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            explanationMethod_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            model_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            feature1_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            feature2_ = s;
            break;
          }
          case 48: {

            numInfluential_ = input.readInt32();
            break;
          }
          case 58: {

            proxyDataset_ = input.readBytes();
            break;
          }
          case 66: {

            query_ = input.readBytes();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            features_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            target_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_ExplanationsRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_ExplanationsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest.class, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest.Builder.class);
  }

  public static final int EXPLANATION_TYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object explanationType_;
  /**
   * <code>string explanation_type = 1;</code>
   */
  public java.lang.String getExplanationType() {
    java.lang.Object ref = explanationType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      explanationType_ = s;
      return s;
    }
  }
  /**
   * <code>string explanation_type = 1;</code>
   */
  public com.google.protobuf.ByteString
      getExplanationTypeBytes() {
    java.lang.Object ref = explanationType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      explanationType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPLANATION_METHOD_FIELD_NUMBER = 2;
  private volatile java.lang.Object explanationMethod_;
  /**
   * <code>string explanation_method = 2;</code>
   */
  public java.lang.String getExplanationMethod() {
    java.lang.Object ref = explanationMethod_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      explanationMethod_ = s;
      return s;
    }
  }
  /**
   * <code>string explanation_method = 2;</code>
   */
  public com.google.protobuf.ByteString
      getExplanationMethodBytes() {
    java.lang.Object ref = explanationMethod_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      explanationMethod_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODEL_FIELD_NUMBER = 3;
  private volatile java.lang.Object model_;
  /**
   * <code>string model = 3;</code>
   */
  public java.lang.String getModel() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      model_ = s;
      return s;
    }
  }
  /**
   * <code>string model = 3;</code>
   */
  public com.google.protobuf.ByteString
      getModelBytes() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      model_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FEATURE1_FIELD_NUMBER = 4;
  private volatile java.lang.Object feature1_;
  /**
   * <code>string feature1 = 4;</code>
   */
  public java.lang.String getFeature1() {
    java.lang.Object ref = feature1_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      feature1_ = s;
      return s;
    }
  }
  /**
   * <code>string feature1 = 4;</code>
   */
  public com.google.protobuf.ByteString
      getFeature1Bytes() {
    java.lang.Object ref = feature1_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      feature1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FEATURE2_FIELD_NUMBER = 5;
  private volatile java.lang.Object feature2_;
  /**
   * <code>string feature2 = 5;</code>
   */
  public java.lang.String getFeature2() {
    java.lang.Object ref = feature2_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      feature2_ = s;
      return s;
    }
  }
  /**
   * <code>string feature2 = 5;</code>
   */
  public com.google.protobuf.ByteString
      getFeature2Bytes() {
    java.lang.Object ref = feature2_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      feature2_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUM_INFLUENTIAL_FIELD_NUMBER = 6;
  private int numInfluential_;
  /**
   * <code>int32 num_influential = 6;</code>
   */
  public int getNumInfluential() {
    return numInfluential_;
  }

  public static final int PROXY_DATASET_FIELD_NUMBER = 7;
  private com.google.protobuf.ByteString proxyDataset_;
  /**
   * <pre>
   * ----- Counterfactual Explanation Fields -----
   * </pre>
   *
   * <code>bytes proxy_dataset = 7;</code>
   */
  public com.google.protobuf.ByteString getProxyDataset() {
    return proxyDataset_;
  }

  public static final int QUERY_FIELD_NUMBER = 8;
  private com.google.protobuf.ByteString query_;
  /**
   * <code>bytes query = 8;</code>
   */
  public com.google.protobuf.ByteString getQuery() {
    return query_;
  }

  public static final int FEATURES_FIELD_NUMBER = 9;
  private volatile java.lang.Object features_;
  /**
   * <pre>
   * ------------ PDP Fields -------------------------
   * the other same as Pipeline Explainability plus
   * </pre>
   *
   * <code>string features = 9;</code>
   */
  public java.lang.String getFeatures() {
    java.lang.Object ref = features_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      features_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ------------ PDP Fields -------------------------
   * the other same as Pipeline Explainability plus
   * </pre>
   *
   * <code>string features = 9;</code>
   */
  public com.google.protobuf.ByteString
      getFeaturesBytes() {
    java.lang.Object ref = features_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      features_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TARGET_FIELD_NUMBER = 10;
  private volatile java.lang.Object target_;
  /**
   * <pre>
   * ------------ CounterfactualExplanations Fields -------------------------
   * same as Model explainability plus target target label 
   * </pre>
   *
   * <code>string target = 10;</code>
   */
  public java.lang.String getTarget() {
    java.lang.Object ref = target_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      target_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ------------ CounterfactualExplanations Fields -------------------------
   * same as Model explainability plus target target label 
   * </pre>
   *
   * <code>string target = 10;</code>
   */
  public com.google.protobuf.ByteString
      getTargetBytes() {
    java.lang.Object ref = target_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      target_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getExplanationTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, explanationType_);
    }
    if (!getExplanationMethodBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, explanationMethod_);
    }
    if (!getModelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, model_);
    }
    if (!getFeature1Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, feature1_);
    }
    if (!getFeature2Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, feature2_);
    }
    if (numInfluential_ != 0) {
      output.writeInt32(6, numInfluential_);
    }
    if (!proxyDataset_.isEmpty()) {
      output.writeBytes(7, proxyDataset_);
    }
    if (!query_.isEmpty()) {
      output.writeBytes(8, query_);
    }
    if (!getFeaturesBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, features_);
    }
    if (!getTargetBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, target_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getExplanationTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, explanationType_);
    }
    if (!getExplanationMethodBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, explanationMethod_);
    }
    if (!getModelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, model_);
    }
    if (!getFeature1Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, feature1_);
    }
    if (!getFeature2Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, feature2_);
    }
    if (numInfluential_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, numInfluential_);
    }
    if (!proxyDataset_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(7, proxyDataset_);
    }
    if (!query_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(8, query_);
    }
    if (!getFeaturesBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, features_);
    }
    if (!getTargetBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, target_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest)) {
      return super.equals(obj);
    }
    gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest other = (gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest) obj;

    boolean result = true;
    result = result && getExplanationType()
        .equals(other.getExplanationType());
    result = result && getExplanationMethod()
        .equals(other.getExplanationMethod());
    result = result && getModel()
        .equals(other.getModel());
    result = result && getFeature1()
        .equals(other.getFeature1());
    result = result && getFeature2()
        .equals(other.getFeature2());
    result = result && (getNumInfluential()
        == other.getNumInfluential());
    result = result && getProxyDataset()
        .equals(other.getProxyDataset());
    result = result && getQuery()
        .equals(other.getQuery());
    result = result && getFeatures()
        .equals(other.getFeatures());
    result = result && getTarget()
        .equals(other.getTarget());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EXPLANATION_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getExplanationType().hashCode();
    hash = (37 * hash) + EXPLANATION_METHOD_FIELD_NUMBER;
    hash = (53 * hash) + getExplanationMethod().hashCode();
    hash = (37 * hash) + MODEL_FIELD_NUMBER;
    hash = (53 * hash) + getModel().hashCode();
    hash = (37 * hash) + FEATURE1_FIELD_NUMBER;
    hash = (53 * hash) + getFeature1().hashCode();
    hash = (37 * hash) + FEATURE2_FIELD_NUMBER;
    hash = (53 * hash) + getFeature2().hashCode();
    hash = (37 * hash) + NUM_INFLUENTIAL_FIELD_NUMBER;
    hash = (53 * hash) + getNumInfluential();
    hash = (37 * hash) + PROXY_DATASET_FIELD_NUMBER;
    hash = (53 * hash) + getProxyDataset().hashCode();
    hash = (37 * hash) + QUERY_FIELD_NUMBER;
    hash = (53 * hash) + getQuery().hashCode();
    hash = (37 * hash) + FEATURES_FIELD_NUMBER;
    hash = (53 * hash) + getFeatures().hashCode();
    hash = (37 * hash) + TARGET_FIELD_NUMBER;
    hash = (53 * hash) + getTarget().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ExplanationsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ExplanationsRequest)
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_ExplanationsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_ExplanationsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest.class, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest.Builder.class);
    }

    // Construct using gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      explanationType_ = "";

      explanationMethod_ = "";

      model_ = "";

      feature1_ = "";

      feature2_ = "";

      numInfluential_ = 0;

      proxyDataset_ = com.google.protobuf.ByteString.EMPTY;

      query_ = com.google.protobuf.ByteString.EMPTY;

      features_ = "";

      target_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_ExplanationsRequest_descriptor;
    }

    public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest getDefaultInstanceForType() {
      return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest.getDefaultInstance();
    }

    public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest build() {
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest buildPartial() {
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest result = new gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest(this);
      result.explanationType_ = explanationType_;
      result.explanationMethod_ = explanationMethod_;
      result.model_ = model_;
      result.feature1_ = feature1_;
      result.feature2_ = feature2_;
      result.numInfluential_ = numInfluential_;
      result.proxyDataset_ = proxyDataset_;
      result.query_ = query_;
      result.features_ = features_;
      result.target_ = target_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest) {
        return mergeFrom((gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest other) {
      if (other == gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest.getDefaultInstance()) return this;
      if (!other.getExplanationType().isEmpty()) {
        explanationType_ = other.explanationType_;
        onChanged();
      }
      if (!other.getExplanationMethod().isEmpty()) {
        explanationMethod_ = other.explanationMethod_;
        onChanged();
      }
      if (!other.getModel().isEmpty()) {
        model_ = other.model_;
        onChanged();
      }
      if (!other.getFeature1().isEmpty()) {
        feature1_ = other.feature1_;
        onChanged();
      }
      if (!other.getFeature2().isEmpty()) {
        feature2_ = other.feature2_;
        onChanged();
      }
      if (other.getNumInfluential() != 0) {
        setNumInfluential(other.getNumInfluential());
      }
      if (other.getProxyDataset() != com.google.protobuf.ByteString.EMPTY) {
        setProxyDataset(other.getProxyDataset());
      }
      if (other.getQuery() != com.google.protobuf.ByteString.EMPTY) {
        setQuery(other.getQuery());
      }
      if (!other.getFeatures().isEmpty()) {
        features_ = other.features_;
        onChanged();
      }
      if (!other.getTarget().isEmpty()) {
        target_ = other.target_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object explanationType_ = "";
    /**
     * <code>string explanation_type = 1;</code>
     */
    public java.lang.String getExplanationType() {
      java.lang.Object ref = explanationType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        explanationType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string explanation_type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getExplanationTypeBytes() {
      java.lang.Object ref = explanationType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        explanationType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string explanation_type = 1;</code>
     */
    public Builder setExplanationType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      explanationType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string explanation_type = 1;</code>
     */
    public Builder clearExplanationType() {
      
      explanationType_ = getDefaultInstance().getExplanationType();
      onChanged();
      return this;
    }
    /**
     * <code>string explanation_type = 1;</code>
     */
    public Builder setExplanationTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      explanationType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object explanationMethod_ = "";
    /**
     * <code>string explanation_method = 2;</code>
     */
    public java.lang.String getExplanationMethod() {
      java.lang.Object ref = explanationMethod_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        explanationMethod_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string explanation_method = 2;</code>
     */
    public com.google.protobuf.ByteString
        getExplanationMethodBytes() {
      java.lang.Object ref = explanationMethod_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        explanationMethod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string explanation_method = 2;</code>
     */
    public Builder setExplanationMethod(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      explanationMethod_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string explanation_method = 2;</code>
     */
    public Builder clearExplanationMethod() {
      
      explanationMethod_ = getDefaultInstance().getExplanationMethod();
      onChanged();
      return this;
    }
    /**
     * <code>string explanation_method = 2;</code>
     */
    public Builder setExplanationMethodBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      explanationMethod_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object model_ = "";
    /**
     * <code>string model = 3;</code>
     */
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        model_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string model = 3;</code>
     */
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string model = 3;</code>
     */
    public Builder setModel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      model_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string model = 3;</code>
     */
    public Builder clearModel() {
      
      model_ = getDefaultInstance().getModel();
      onChanged();
      return this;
    }
    /**
     * <code>string model = 3;</code>
     */
    public Builder setModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      model_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object feature1_ = "";
    /**
     * <code>string feature1 = 4;</code>
     */
    public java.lang.String getFeature1() {
      java.lang.Object ref = feature1_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        feature1_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string feature1 = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFeature1Bytes() {
      java.lang.Object ref = feature1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        feature1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string feature1 = 4;</code>
     */
    public Builder setFeature1(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      feature1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string feature1 = 4;</code>
     */
    public Builder clearFeature1() {
      
      feature1_ = getDefaultInstance().getFeature1();
      onChanged();
      return this;
    }
    /**
     * <code>string feature1 = 4;</code>
     */
    public Builder setFeature1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      feature1_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object feature2_ = "";
    /**
     * <code>string feature2 = 5;</code>
     */
    public java.lang.String getFeature2() {
      java.lang.Object ref = feature2_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        feature2_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string feature2 = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFeature2Bytes() {
      java.lang.Object ref = feature2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        feature2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string feature2 = 5;</code>
     */
    public Builder setFeature2(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      feature2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string feature2 = 5;</code>
     */
    public Builder clearFeature2() {
      
      feature2_ = getDefaultInstance().getFeature2();
      onChanged();
      return this;
    }
    /**
     * <code>string feature2 = 5;</code>
     */
    public Builder setFeature2Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      feature2_ = value;
      onChanged();
      return this;
    }

    private int numInfluential_ ;
    /**
     * <code>int32 num_influential = 6;</code>
     */
    public int getNumInfluential() {
      return numInfluential_;
    }
    /**
     * <code>int32 num_influential = 6;</code>
     */
    public Builder setNumInfluential(int value) {
      
      numInfluential_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 num_influential = 6;</code>
     */
    public Builder clearNumInfluential() {
      
      numInfluential_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString proxyDataset_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * ----- Counterfactual Explanation Fields -----
     * </pre>
     *
     * <code>bytes proxy_dataset = 7;</code>
     */
    public com.google.protobuf.ByteString getProxyDataset() {
      return proxyDataset_;
    }
    /**
     * <pre>
     * ----- Counterfactual Explanation Fields -----
     * </pre>
     *
     * <code>bytes proxy_dataset = 7;</code>
     */
    public Builder setProxyDataset(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      proxyDataset_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ----- Counterfactual Explanation Fields -----
     * </pre>
     *
     * <code>bytes proxy_dataset = 7;</code>
     */
    public Builder clearProxyDataset() {
      
      proxyDataset_ = getDefaultInstance().getProxyDataset();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString query_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes query = 8;</code>
     */
    public com.google.protobuf.ByteString getQuery() {
      return query_;
    }
    /**
     * <code>bytes query = 8;</code>
     */
    public Builder setQuery(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      query_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes query = 8;</code>
     */
    public Builder clearQuery() {
      
      query_ = getDefaultInstance().getQuery();
      onChanged();
      return this;
    }

    private java.lang.Object features_ = "";
    /**
     * <pre>
     * ------------ PDP Fields -------------------------
     * the other same as Pipeline Explainability plus
     * </pre>
     *
     * <code>string features = 9;</code>
     */
    public java.lang.String getFeatures() {
      java.lang.Object ref = features_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        features_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ------------ PDP Fields -------------------------
     * the other same as Pipeline Explainability plus
     * </pre>
     *
     * <code>string features = 9;</code>
     */
    public com.google.protobuf.ByteString
        getFeaturesBytes() {
      java.lang.Object ref = features_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        features_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ------------ PDP Fields -------------------------
     * the other same as Pipeline Explainability plus
     * </pre>
     *
     * <code>string features = 9;</code>
     */
    public Builder setFeatures(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      features_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ------------ PDP Fields -------------------------
     * the other same as Pipeline Explainability plus
     * </pre>
     *
     * <code>string features = 9;</code>
     */
    public Builder clearFeatures() {
      
      features_ = getDefaultInstance().getFeatures();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ------------ PDP Fields -------------------------
     * the other same as Pipeline Explainability plus
     * </pre>
     *
     * <code>string features = 9;</code>
     */
    public Builder setFeaturesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      features_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object target_ = "";
    /**
     * <pre>
     * ------------ CounterfactualExplanations Fields -------------------------
     * same as Model explainability plus target target label 
     * </pre>
     *
     * <code>string target = 10;</code>
     */
    public java.lang.String getTarget() {
      java.lang.Object ref = target_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        target_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ------------ CounterfactualExplanations Fields -------------------------
     * same as Model explainability plus target target label 
     * </pre>
     *
     * <code>string target = 10;</code>
     */
    public com.google.protobuf.ByteString
        getTargetBytes() {
      java.lang.Object ref = target_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        target_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ------------ CounterfactualExplanations Fields -------------------------
     * same as Model explainability plus target target label 
     * </pre>
     *
     * <code>string target = 10;</code>
     */
    public Builder setTarget(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      target_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ------------ CounterfactualExplanations Fields -------------------------
     * same as Model explainability plus target target label 
     * </pre>
     *
     * <code>string target = 10;</code>
     */
    public Builder clearTarget() {
      
      target_ = getDefaultInstance().getTarget();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ------------ CounterfactualExplanations Fields -------------------------
     * same as Model explainability plus target target label 
     * </pre>
     *
     * <code>string target = 10;</code>
     */
    public Builder setTargetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      target_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:ExplanationsRequest)
  }

  // @@protoc_insertion_point(class_scope:ExplanationsRequest)
  private static final gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest();
  }

  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExplanationsRequest>
      PARSER = new com.google.protobuf.AbstractParser<ExplanationsRequest>() {
    public ExplanationsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExplanationsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExplanationsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExplanationsRequest> getParserForType() {
    return PARSER;
  }

  public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

