package gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated;

import static io.grpc.stub.ClientCalls.asyncUnaryCall;
import static io.grpc.stub.ClientCalls.asyncServerStreamingCall;
import static io.grpc.stub.ClientCalls.asyncClientStreamingCall;
import static io.grpc.stub.ClientCalls.asyncBidiStreamingCall;
import static io.grpc.stub.ClientCalls.blockingUnaryCall;
import static io.grpc.stub.ClientCalls.blockingServerStreamingCall;
import static io.grpc.stub.ClientCalls.futureUnaryCall;
import static io.grpc.MethodDescriptor.generateFullMethodName;
import static io.grpc.stub.ServerCalls.asyncUnaryCall;
import static io.grpc.stub.ServerCalls.asyncServerStreamingCall;
import static io.grpc.stub.ServerCalls.asyncClientStreamingCall;
import static io.grpc.stub.ServerCalls.asyncBidiStreamingCall;
import static io.grpc.stub.ServerCalls.asyncUnimplementedUnaryCall;
import static io.grpc.stub.ServerCalls.asyncUnimplementedStreamingCall;

/**
 */
@javax.annotation.Generated(
    value = "by gRPC proto compiler (version 1.4.0)",
    comments = "Source: xai_service.proto")
public final class ExplanationsGrpc {

  private ExplanationsGrpc() {}

  public static final String SERVICE_NAME = "Explanations";

  // Static method descriptors that strictly reflect the proto.
  @io.grpc.ExperimentalApi("https://github.com/grpc/grpc-java/issues/1901")
  public static final io.grpc.MethodDescriptor<gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest,
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> METHOD_GET_EXPLANATION =
      io.grpc.MethodDescriptor.<gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse>newBuilder()
          .setType(io.grpc.MethodDescriptor.MethodType.UNARY)
          .setFullMethodName(generateFullMethodName(
              "Explanations", "GetExplanation"))
          .setRequestMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
              gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest.getDefaultInstance()))
          .setResponseMarshaller(io.grpc.protobuf.ProtoUtils.marshaller(
              gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse.getDefaultInstance()))
          .build();

  /**
   * Creates a new async stub that supports all call types for the service
   */
  public static ExplanationsStub newStub(io.grpc.Channel channel) {
    return new ExplanationsStub(channel);
  }

  /**
   * Creates a new blocking-style stub that supports unary and streaming output calls on the service
   */
  public static ExplanationsBlockingStub newBlockingStub(
      io.grpc.Channel channel) {
    return new ExplanationsBlockingStub(channel);
  }

  /**
   * Creates a new ListenableFuture-style stub that supports unary calls on the service
   */
  public static ExplanationsFutureStub newFutureStub(
      io.grpc.Channel channel) {
    return new ExplanationsFutureStub(channel);
  }

  /**
   */
  public static abstract class ExplanationsImplBase implements io.grpc.BindableService {

    /**
     */
    public void getExplanation(gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest request,
        io.grpc.stub.StreamObserver<gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> responseObserver) {
      asyncUnimplementedUnaryCall(METHOD_GET_EXPLANATION, responseObserver);
    }

    @java.lang.Override public final io.grpc.ServerServiceDefinition bindService() {
      return io.grpc.ServerServiceDefinition.builder(getServiceDescriptor())
          .addMethod(
            METHOD_GET_EXPLANATION,
            asyncUnaryCall(
              new MethodHandlers<
                gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest,
                gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse>(
                  this, METHODID_GET_EXPLANATION)))
          .build();
    }
  }

  /**
   */
  public static final class ExplanationsStub extends io.grpc.stub.AbstractStub<ExplanationsStub> {
    private ExplanationsStub(io.grpc.Channel channel) {
      super(channel);
    }

    private ExplanationsStub(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      super(channel, callOptions);
    }

    @java.lang.Override
    protected ExplanationsStub build(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      return new ExplanationsStub(channel, callOptions);
    }

    /**
     */
    public void getExplanation(gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest request,
        io.grpc.stub.StreamObserver<gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> responseObserver) {
      asyncUnaryCall(
          getChannel().newCall(METHOD_GET_EXPLANATION, getCallOptions()), request, responseObserver);
    }
  }

  /**
   */
  public static final class ExplanationsBlockingStub extends io.grpc.stub.AbstractStub<ExplanationsBlockingStub> {
    private ExplanationsBlockingStub(io.grpc.Channel channel) {
      super(channel);
    }

    private ExplanationsBlockingStub(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      super(channel, callOptions);
    }

    @java.lang.Override
    protected ExplanationsBlockingStub build(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      return new ExplanationsBlockingStub(channel, callOptions);
    }

    /**
     */
    public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse getExplanation(gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest request) {
      return blockingUnaryCall(
          getChannel(), METHOD_GET_EXPLANATION, getCallOptions(), request);
    }
  }

  /**
   */
  public static final class ExplanationsFutureStub extends io.grpc.stub.AbstractStub<ExplanationsFutureStub> {
    private ExplanationsFutureStub(io.grpc.Channel channel) {
      super(channel);
    }

    private ExplanationsFutureStub(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      super(channel, callOptions);
    }

    @java.lang.Override
    protected ExplanationsFutureStub build(io.grpc.Channel channel,
        io.grpc.CallOptions callOptions) {
      return new ExplanationsFutureStub(channel, callOptions);
    }

    /**
     */
    public com.google.common.util.concurrent.ListenableFuture<gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> getExplanation(
        gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest request) {
      return futureUnaryCall(
          getChannel().newCall(METHOD_GET_EXPLANATION, getCallOptions()), request);
    }
  }

  private static final int METHODID_GET_EXPLANATION = 0;

  private static final class MethodHandlers<Req, Resp> implements
      io.grpc.stub.ServerCalls.UnaryMethod<Req, Resp>,
      io.grpc.stub.ServerCalls.ServerStreamingMethod<Req, Resp>,
      io.grpc.stub.ServerCalls.ClientStreamingMethod<Req, Resp>,
      io.grpc.stub.ServerCalls.BidiStreamingMethod<Req, Resp> {
    private final ExplanationsImplBase serviceImpl;
    private final int methodId;

    MethodHandlers(ExplanationsImplBase serviceImpl, int methodId) {
      this.serviceImpl = serviceImpl;
      this.methodId = methodId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("unchecked")
    public void invoke(Req request, io.grpc.stub.StreamObserver<Resp> responseObserver) {
      switch (methodId) {
        case METHODID_GET_EXPLANATION:
          serviceImpl.getExplanation((gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsRequest) request,
              (io.grpc.stub.StreamObserver<gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse>) responseObserver);
          break;
        default:
          throw new AssertionError();
      }
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("unchecked")
    public io.grpc.stub.StreamObserver<Req> invoke(
        io.grpc.stub.StreamObserver<Resp> responseObserver) {
      switch (methodId) {
        default:
          throw new AssertionError();
      }
    }
  }

  private static final class ExplanationsDescriptorSupplier implements io.grpc.protobuf.ProtoFileDescriptorSupplier {
    @java.lang.Override
    public com.google.protobuf.Descriptors.FileDescriptor getFileDescriptor() {
      return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.getDescriptor();
    }
  }

  private static volatile io.grpc.ServiceDescriptor serviceDescriptor;

  public static io.grpc.ServiceDescriptor getServiceDescriptor() {
    io.grpc.ServiceDescriptor result = serviceDescriptor;
    if (result == null) {
      synchronized (ExplanationsGrpc.class) {
        result = serviceDescriptor;
        if (result == null) {
          serviceDescriptor = result = io.grpc.ServiceDescriptor.newBuilder(SERVICE_NAME)
              .setSchemaDescriptor(new ExplanationsDescriptorSupplier())
              .addMethod(METHOD_GET_EXPLANATION)
              .build();
        }
      }
    }
    return result;
  }
}
