// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xai_service.proto

package gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated;

/**
 * <pre>
 *------------------ Pipeline Explainability --------------------------------------------------
 * </pre>
 *
 * Protobuf type {@code ExplanationsResponse}
 */
public  final class ExplanationsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ExplanationsResponse)
    ExplanationsResponseOrBuilder {
  // Use ExplanationsResponse.newBuilder() to construct.
  private ExplanationsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExplanationsResponse() {
    pdpHpValues_ = "";
    pdpValues_ = "";
    pdp2DXi_ = "";
    pdp2DYi_ = "";
    pdp2DZi_ = "";
    aleData_ = "";
    positive_ = "";
    negative_ = "";
    cfs_ = "";
    pdpVals_ = "";
    pdpEffect_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ExplanationsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            pdpHpValues_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            pdpValues_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            pdp2DXi_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            pdp2DYi_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            pdp2DZi_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            aleData_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            positive_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            negative_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            cfs_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            pdpVals_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            pdpEffect_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_ExplanationsResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_ExplanationsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse.class, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse.Builder.class);
  }

  public static final int PDP_HP_VALUES_FIELD_NUMBER = 1;
  private volatile java.lang.Object pdpHpValues_;
  /**
   * <pre>
   * Fields specific to ComputePDP explanation
   * </pre>
   *
   * <code>string pdp_hp_values = 1;</code>
   */
  public java.lang.String getPdpHpValues() {
    java.lang.Object ref = pdpHpValues_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pdpHpValues_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Fields specific to ComputePDP explanation
   * </pre>
   *
   * <code>string pdp_hp_values = 1;</code>
   */
  public com.google.protobuf.ByteString
      getPdpHpValuesBytes() {
    java.lang.Object ref = pdpHpValues_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pdpHpValues_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PDP_VALUES_FIELD_NUMBER = 2;
  private volatile java.lang.Object pdpValues_;
  /**
   * <code>string pdp_values = 2;</code>
   */
  public java.lang.String getPdpValues() {
    java.lang.Object ref = pdpValues_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pdpValues_ = s;
      return s;
    }
  }
  /**
   * <code>string pdp_values = 2;</code>
   */
  public com.google.protobuf.ByteString
      getPdpValuesBytes() {
    java.lang.Object ref = pdpValues_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pdpValues_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PDP2D_XI_FIELD_NUMBER = 3;
  private volatile java.lang.Object pdp2DXi_;
  /**
   * <pre>
   * Fields specific to ComputePDP2D explanation
   * </pre>
   *
   * <code>string pdp2d_xi = 3;</code>
   */
  public java.lang.String getPdp2DXi() {
    java.lang.Object ref = pdp2DXi_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pdp2DXi_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Fields specific to ComputePDP2D explanation
   * </pre>
   *
   * <code>string pdp2d_xi = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPdp2DXiBytes() {
    java.lang.Object ref = pdp2DXi_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pdp2DXi_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PDP2D_YI_FIELD_NUMBER = 4;
  private volatile java.lang.Object pdp2DYi_;
  /**
   * <code>string pdp2d_yi = 4;</code>
   */
  public java.lang.String getPdp2DYi() {
    java.lang.Object ref = pdp2DYi_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pdp2DYi_ = s;
      return s;
    }
  }
  /**
   * <code>string pdp2d_yi = 4;</code>
   */
  public com.google.protobuf.ByteString
      getPdp2DYiBytes() {
    java.lang.Object ref = pdp2DYi_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pdp2DYi_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PDP2D_ZI_FIELD_NUMBER = 5;
  private volatile java.lang.Object pdp2DZi_;
  /**
   * <code>string pdp2d_zi = 5;</code>
   */
  public java.lang.String getPdp2DZi() {
    java.lang.Object ref = pdp2DZi_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pdp2DZi_ = s;
      return s;
    }
  }
  /**
   * <code>string pdp2d_zi = 5;</code>
   */
  public com.google.protobuf.ByteString
      getPdp2DZiBytes() {
    java.lang.Object ref = pdp2DZi_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pdp2DZi_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALE_DATA_FIELD_NUMBER = 6;
  private volatile java.lang.Object aleData_;
  /**
   * <pre>
   * Fields specific to ComputeALE explanation
   * </pre>
   *
   * <code>string ale_data = 6;</code>
   */
  public java.lang.String getAleData() {
    java.lang.Object ref = aleData_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      aleData_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Fields specific to ComputeALE explanation
   * </pre>
   *
   * <code>string ale_data = 6;</code>
   */
  public com.google.protobuf.ByteString
      getAleDataBytes() {
    java.lang.Object ref = aleData_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      aleData_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSITIVE_FIELD_NUMBER = 7;
  private volatile java.lang.Object positive_;
  /**
   * <pre>
   * Fields specific to InfluenceFunction explanation
   * </pre>
   *
   * <code>string positive = 7;</code>
   */
  public java.lang.String getPositive() {
    java.lang.Object ref = positive_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      positive_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Fields specific to InfluenceFunction explanation
   * </pre>
   *
   * <code>string positive = 7;</code>
   */
  public com.google.protobuf.ByteString
      getPositiveBytes() {
    java.lang.Object ref = positive_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      positive_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NEGATIVE_FIELD_NUMBER = 8;
  private volatile java.lang.Object negative_;
  /**
   * <code>string negative = 8;</code>
   */
  public java.lang.String getNegative() {
    java.lang.Object ref = negative_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      negative_ = s;
      return s;
    }
  }
  /**
   * <code>string negative = 8;</code>
   */
  public com.google.protobuf.ByteString
      getNegativeBytes() {
    java.lang.Object ref = negative_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      negative_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CFS_FIELD_NUMBER = 9;
  private volatile java.lang.Object cfs_;
  /**
   * <pre>
   * Fields specific to Counterfactual Explanations
   * </pre>
   *
   * <code>string cfs = 9;</code>
   */
  public java.lang.String getCfs() {
    java.lang.Object ref = cfs_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cfs_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Fields specific to Counterfactual Explanations
   * </pre>
   *
   * <code>string cfs = 9;</code>
   */
  public com.google.protobuf.ByteString
      getCfsBytes() {
    java.lang.Object ref = cfs_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cfs_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PDP_VALS_FIELD_NUMBER = 10;
  private volatile java.lang.Object pdpVals_;
  /**
   * <pre>
   *------------------ Model Explainability --------------------------------------------------
   * ------------ PDP Fields -------------------------
   * </pre>
   *
   * <code>string pdp_vals = 10;</code>
   */
  public java.lang.String getPdpVals() {
    java.lang.Object ref = pdpVals_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pdpVals_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *------------------ Model Explainability --------------------------------------------------
   * ------------ PDP Fields -------------------------
   * </pre>
   *
   * <code>string pdp_vals = 10;</code>
   */
  public com.google.protobuf.ByteString
      getPdpValsBytes() {
    java.lang.Object ref = pdpVals_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pdpVals_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PDP_EFFECT_FIELD_NUMBER = 11;
  private volatile java.lang.Object pdpEffect_;
  /**
   * <code>string pdp_effect = 11;</code>
   */
  public java.lang.String getPdpEffect() {
    java.lang.Object ref = pdpEffect_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pdpEffect_ = s;
      return s;
    }
  }
  /**
   * <code>string pdp_effect = 11;</code>
   */
  public com.google.protobuf.ByteString
      getPdpEffectBytes() {
    java.lang.Object ref = pdpEffect_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pdpEffect_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getPdpHpValuesBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pdpHpValues_);
    }
    if (!getPdpValuesBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, pdpValues_);
    }
    if (!getPdp2DXiBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, pdp2DXi_);
    }
    if (!getPdp2DYiBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, pdp2DYi_);
    }
    if (!getPdp2DZiBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, pdp2DZi_);
    }
    if (!getAleDataBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, aleData_);
    }
    if (!getPositiveBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, positive_);
    }
    if (!getNegativeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, negative_);
    }
    if (!getCfsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, cfs_);
    }
    if (!getPdpValsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, pdpVals_);
    }
    if (!getPdpEffectBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, pdpEffect_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPdpHpValuesBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pdpHpValues_);
    }
    if (!getPdpValuesBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, pdpValues_);
    }
    if (!getPdp2DXiBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, pdp2DXi_);
    }
    if (!getPdp2DYiBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, pdp2DYi_);
    }
    if (!getPdp2DZiBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, pdp2DZi_);
    }
    if (!getAleDataBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, aleData_);
    }
    if (!getPositiveBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, positive_);
    }
    if (!getNegativeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, negative_);
    }
    if (!getCfsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, cfs_);
    }
    if (!getPdpValsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, pdpVals_);
    }
    if (!getPdpEffectBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, pdpEffect_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse)) {
      return super.equals(obj);
    }
    gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse other = (gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse) obj;

    boolean result = true;
    result = result && getPdpHpValues()
        .equals(other.getPdpHpValues());
    result = result && getPdpValues()
        .equals(other.getPdpValues());
    result = result && getPdp2DXi()
        .equals(other.getPdp2DXi());
    result = result && getPdp2DYi()
        .equals(other.getPdp2DYi());
    result = result && getPdp2DZi()
        .equals(other.getPdp2DZi());
    result = result && getAleData()
        .equals(other.getAleData());
    result = result && getPositive()
        .equals(other.getPositive());
    result = result && getNegative()
        .equals(other.getNegative());
    result = result && getCfs()
        .equals(other.getCfs());
    result = result && getPdpVals()
        .equals(other.getPdpVals());
    result = result && getPdpEffect()
        .equals(other.getPdpEffect());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PDP_HP_VALUES_FIELD_NUMBER;
    hash = (53 * hash) + getPdpHpValues().hashCode();
    hash = (37 * hash) + PDP_VALUES_FIELD_NUMBER;
    hash = (53 * hash) + getPdpValues().hashCode();
    hash = (37 * hash) + PDP2D_XI_FIELD_NUMBER;
    hash = (53 * hash) + getPdp2DXi().hashCode();
    hash = (37 * hash) + PDP2D_YI_FIELD_NUMBER;
    hash = (53 * hash) + getPdp2DYi().hashCode();
    hash = (37 * hash) + PDP2D_ZI_FIELD_NUMBER;
    hash = (53 * hash) + getPdp2DZi().hashCode();
    hash = (37 * hash) + ALE_DATA_FIELD_NUMBER;
    hash = (53 * hash) + getAleData().hashCode();
    hash = (37 * hash) + POSITIVE_FIELD_NUMBER;
    hash = (53 * hash) + getPositive().hashCode();
    hash = (37 * hash) + NEGATIVE_FIELD_NUMBER;
    hash = (53 * hash) + getNegative().hashCode();
    hash = (37 * hash) + CFS_FIELD_NUMBER;
    hash = (53 * hash) + getCfs().hashCode();
    hash = (37 * hash) + PDP_VALS_FIELD_NUMBER;
    hash = (53 * hash) + getPdpVals().hashCode();
    hash = (37 * hash) + PDP_EFFECT_FIELD_NUMBER;
    hash = (53 * hash) + getPdpEffect().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *------------------ Pipeline Explainability --------------------------------------------------
   * </pre>
   *
   * Protobuf type {@code ExplanationsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ExplanationsResponse)
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_ExplanationsResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_ExplanationsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse.class, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse.Builder.class);
    }

    // Construct using gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      pdpHpValues_ = "";

      pdpValues_ = "";

      pdp2DXi_ = "";

      pdp2DYi_ = "";

      pdp2DZi_ = "";

      aleData_ = "";

      positive_ = "";

      negative_ = "";

      cfs_ = "";

      pdpVals_ = "";

      pdpEffect_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_ExplanationsResponse_descriptor;
    }

    public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse getDefaultInstanceForType() {
      return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse.getDefaultInstance();
    }

    public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse build() {
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse buildPartial() {
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse result = new gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse(this);
      result.pdpHpValues_ = pdpHpValues_;
      result.pdpValues_ = pdpValues_;
      result.pdp2DXi_ = pdp2DXi_;
      result.pdp2DYi_ = pdp2DYi_;
      result.pdp2DZi_ = pdp2DZi_;
      result.aleData_ = aleData_;
      result.positive_ = positive_;
      result.negative_ = negative_;
      result.cfs_ = cfs_;
      result.pdpVals_ = pdpVals_;
      result.pdpEffect_ = pdpEffect_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse) {
        return mergeFrom((gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse other) {
      if (other == gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse.getDefaultInstance()) return this;
      if (!other.getPdpHpValues().isEmpty()) {
        pdpHpValues_ = other.pdpHpValues_;
        onChanged();
      }
      if (!other.getPdpValues().isEmpty()) {
        pdpValues_ = other.pdpValues_;
        onChanged();
      }
      if (!other.getPdp2DXi().isEmpty()) {
        pdp2DXi_ = other.pdp2DXi_;
        onChanged();
      }
      if (!other.getPdp2DYi().isEmpty()) {
        pdp2DYi_ = other.pdp2DYi_;
        onChanged();
      }
      if (!other.getPdp2DZi().isEmpty()) {
        pdp2DZi_ = other.pdp2DZi_;
        onChanged();
      }
      if (!other.getAleData().isEmpty()) {
        aleData_ = other.aleData_;
        onChanged();
      }
      if (!other.getPositive().isEmpty()) {
        positive_ = other.positive_;
        onChanged();
      }
      if (!other.getNegative().isEmpty()) {
        negative_ = other.negative_;
        onChanged();
      }
      if (!other.getCfs().isEmpty()) {
        cfs_ = other.cfs_;
        onChanged();
      }
      if (!other.getPdpVals().isEmpty()) {
        pdpVals_ = other.pdpVals_;
        onChanged();
      }
      if (!other.getPdpEffect().isEmpty()) {
        pdpEffect_ = other.pdpEffect_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object pdpHpValues_ = "";
    /**
     * <pre>
     * Fields specific to ComputePDP explanation
     * </pre>
     *
     * <code>string pdp_hp_values = 1;</code>
     */
    public java.lang.String getPdpHpValues() {
      java.lang.Object ref = pdpHpValues_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pdpHpValues_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Fields specific to ComputePDP explanation
     * </pre>
     *
     * <code>string pdp_hp_values = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPdpHpValuesBytes() {
      java.lang.Object ref = pdpHpValues_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pdpHpValues_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Fields specific to ComputePDP explanation
     * </pre>
     *
     * <code>string pdp_hp_values = 1;</code>
     */
    public Builder setPdpHpValues(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pdpHpValues_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Fields specific to ComputePDP explanation
     * </pre>
     *
     * <code>string pdp_hp_values = 1;</code>
     */
    public Builder clearPdpHpValues() {
      
      pdpHpValues_ = getDefaultInstance().getPdpHpValues();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Fields specific to ComputePDP explanation
     * </pre>
     *
     * <code>string pdp_hp_values = 1;</code>
     */
    public Builder setPdpHpValuesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pdpHpValues_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object pdpValues_ = "";
    /**
     * <code>string pdp_values = 2;</code>
     */
    public java.lang.String getPdpValues() {
      java.lang.Object ref = pdpValues_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pdpValues_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pdp_values = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPdpValuesBytes() {
      java.lang.Object ref = pdpValues_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pdpValues_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pdp_values = 2;</code>
     */
    public Builder setPdpValues(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pdpValues_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pdp_values = 2;</code>
     */
    public Builder clearPdpValues() {
      
      pdpValues_ = getDefaultInstance().getPdpValues();
      onChanged();
      return this;
    }
    /**
     * <code>string pdp_values = 2;</code>
     */
    public Builder setPdpValuesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pdpValues_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object pdp2DXi_ = "";
    /**
     * <pre>
     * Fields specific to ComputePDP2D explanation
     * </pre>
     *
     * <code>string pdp2d_xi = 3;</code>
     */
    public java.lang.String getPdp2DXi() {
      java.lang.Object ref = pdp2DXi_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pdp2DXi_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Fields specific to ComputePDP2D explanation
     * </pre>
     *
     * <code>string pdp2d_xi = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPdp2DXiBytes() {
      java.lang.Object ref = pdp2DXi_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pdp2DXi_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Fields specific to ComputePDP2D explanation
     * </pre>
     *
     * <code>string pdp2d_xi = 3;</code>
     */
    public Builder setPdp2DXi(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pdp2DXi_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Fields specific to ComputePDP2D explanation
     * </pre>
     *
     * <code>string pdp2d_xi = 3;</code>
     */
    public Builder clearPdp2DXi() {
      
      pdp2DXi_ = getDefaultInstance().getPdp2DXi();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Fields specific to ComputePDP2D explanation
     * </pre>
     *
     * <code>string pdp2d_xi = 3;</code>
     */
    public Builder setPdp2DXiBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pdp2DXi_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object pdp2DYi_ = "";
    /**
     * <code>string pdp2d_yi = 4;</code>
     */
    public java.lang.String getPdp2DYi() {
      java.lang.Object ref = pdp2DYi_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pdp2DYi_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pdp2d_yi = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPdp2DYiBytes() {
      java.lang.Object ref = pdp2DYi_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pdp2DYi_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pdp2d_yi = 4;</code>
     */
    public Builder setPdp2DYi(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pdp2DYi_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pdp2d_yi = 4;</code>
     */
    public Builder clearPdp2DYi() {
      
      pdp2DYi_ = getDefaultInstance().getPdp2DYi();
      onChanged();
      return this;
    }
    /**
     * <code>string pdp2d_yi = 4;</code>
     */
    public Builder setPdp2DYiBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pdp2DYi_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object pdp2DZi_ = "";
    /**
     * <code>string pdp2d_zi = 5;</code>
     */
    public java.lang.String getPdp2DZi() {
      java.lang.Object ref = pdp2DZi_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pdp2DZi_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pdp2d_zi = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPdp2DZiBytes() {
      java.lang.Object ref = pdp2DZi_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pdp2DZi_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pdp2d_zi = 5;</code>
     */
    public Builder setPdp2DZi(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pdp2DZi_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pdp2d_zi = 5;</code>
     */
    public Builder clearPdp2DZi() {
      
      pdp2DZi_ = getDefaultInstance().getPdp2DZi();
      onChanged();
      return this;
    }
    /**
     * <code>string pdp2d_zi = 5;</code>
     */
    public Builder setPdp2DZiBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pdp2DZi_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object aleData_ = "";
    /**
     * <pre>
     * Fields specific to ComputeALE explanation
     * </pre>
     *
     * <code>string ale_data = 6;</code>
     */
    public java.lang.String getAleData() {
      java.lang.Object ref = aleData_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        aleData_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Fields specific to ComputeALE explanation
     * </pre>
     *
     * <code>string ale_data = 6;</code>
     */
    public com.google.protobuf.ByteString
        getAleDataBytes() {
      java.lang.Object ref = aleData_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aleData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Fields specific to ComputeALE explanation
     * </pre>
     *
     * <code>string ale_data = 6;</code>
     */
    public Builder setAleData(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      aleData_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Fields specific to ComputeALE explanation
     * </pre>
     *
     * <code>string ale_data = 6;</code>
     */
    public Builder clearAleData() {
      
      aleData_ = getDefaultInstance().getAleData();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Fields specific to ComputeALE explanation
     * </pre>
     *
     * <code>string ale_data = 6;</code>
     */
    public Builder setAleDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      aleData_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object positive_ = "";
    /**
     * <pre>
     * Fields specific to InfluenceFunction explanation
     * </pre>
     *
     * <code>string positive = 7;</code>
     */
    public java.lang.String getPositive() {
      java.lang.Object ref = positive_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        positive_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Fields specific to InfluenceFunction explanation
     * </pre>
     *
     * <code>string positive = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPositiveBytes() {
      java.lang.Object ref = positive_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        positive_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Fields specific to InfluenceFunction explanation
     * </pre>
     *
     * <code>string positive = 7;</code>
     */
    public Builder setPositive(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      positive_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Fields specific to InfluenceFunction explanation
     * </pre>
     *
     * <code>string positive = 7;</code>
     */
    public Builder clearPositive() {
      
      positive_ = getDefaultInstance().getPositive();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Fields specific to InfluenceFunction explanation
     * </pre>
     *
     * <code>string positive = 7;</code>
     */
    public Builder setPositiveBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      positive_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object negative_ = "";
    /**
     * <code>string negative = 8;</code>
     */
    public java.lang.String getNegative() {
      java.lang.Object ref = negative_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        negative_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string negative = 8;</code>
     */
    public com.google.protobuf.ByteString
        getNegativeBytes() {
      java.lang.Object ref = negative_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        negative_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string negative = 8;</code>
     */
    public Builder setNegative(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      negative_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string negative = 8;</code>
     */
    public Builder clearNegative() {
      
      negative_ = getDefaultInstance().getNegative();
      onChanged();
      return this;
    }
    /**
     * <code>string negative = 8;</code>
     */
    public Builder setNegativeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      negative_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cfs_ = "";
    /**
     * <pre>
     * Fields specific to Counterfactual Explanations
     * </pre>
     *
     * <code>string cfs = 9;</code>
     */
    public java.lang.String getCfs() {
      java.lang.Object ref = cfs_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cfs_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Fields specific to Counterfactual Explanations
     * </pre>
     *
     * <code>string cfs = 9;</code>
     */
    public com.google.protobuf.ByteString
        getCfsBytes() {
      java.lang.Object ref = cfs_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cfs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Fields specific to Counterfactual Explanations
     * </pre>
     *
     * <code>string cfs = 9;</code>
     */
    public Builder setCfs(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cfs_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Fields specific to Counterfactual Explanations
     * </pre>
     *
     * <code>string cfs = 9;</code>
     */
    public Builder clearCfs() {
      
      cfs_ = getDefaultInstance().getCfs();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Fields specific to Counterfactual Explanations
     * </pre>
     *
     * <code>string cfs = 9;</code>
     */
    public Builder setCfsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cfs_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object pdpVals_ = "";
    /**
     * <pre>
     *------------------ Model Explainability --------------------------------------------------
     * ------------ PDP Fields -------------------------
     * </pre>
     *
     * <code>string pdp_vals = 10;</code>
     */
    public java.lang.String getPdpVals() {
      java.lang.Object ref = pdpVals_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pdpVals_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *------------------ Model Explainability --------------------------------------------------
     * ------------ PDP Fields -------------------------
     * </pre>
     *
     * <code>string pdp_vals = 10;</code>
     */
    public com.google.protobuf.ByteString
        getPdpValsBytes() {
      java.lang.Object ref = pdpVals_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pdpVals_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *------------------ Model Explainability --------------------------------------------------
     * ------------ PDP Fields -------------------------
     * </pre>
     *
     * <code>string pdp_vals = 10;</code>
     */
    public Builder setPdpVals(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pdpVals_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *------------------ Model Explainability --------------------------------------------------
     * ------------ PDP Fields -------------------------
     * </pre>
     *
     * <code>string pdp_vals = 10;</code>
     */
    public Builder clearPdpVals() {
      
      pdpVals_ = getDefaultInstance().getPdpVals();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *------------------ Model Explainability --------------------------------------------------
     * ------------ PDP Fields -------------------------
     * </pre>
     *
     * <code>string pdp_vals = 10;</code>
     */
    public Builder setPdpValsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pdpVals_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object pdpEffect_ = "";
    /**
     * <code>string pdp_effect = 11;</code>
     */
    public java.lang.String getPdpEffect() {
      java.lang.Object ref = pdpEffect_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pdpEffect_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pdp_effect = 11;</code>
     */
    public com.google.protobuf.ByteString
        getPdpEffectBytes() {
      java.lang.Object ref = pdpEffect_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pdpEffect_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pdp_effect = 11;</code>
     */
    public Builder setPdpEffect(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pdpEffect_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pdp_effect = 11;</code>
     */
    public Builder clearPdpEffect() {
      
      pdpEffect_ = getDefaultInstance().getPdpEffect();
      onChanged();
      return this;
    }
    /**
     * <code>string pdp_effect = 11;</code>
     */
    public Builder setPdpEffectBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pdpEffect_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:ExplanationsResponse)
  }

  // @@protoc_insertion_point(class_scope:ExplanationsResponse)
  private static final gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse();
  }

  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExplanationsResponse>
      PARSER = new com.google.protobuf.AbstractParser<ExplanationsResponse>() {
    public ExplanationsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExplanationsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExplanationsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExplanationsResponse> getParserForType() {
    return PARSER;
  }

  public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

