// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xai_service.proto

package gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated;

public interface ExplanationsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ExplanationsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string explainability_type = 1;</code>
   */
  java.lang.String getExplainabilityType();
  /**
   * <code>string explainability_type = 1;</code>
   */
  com.google.protobuf.ByteString
      getExplainabilityTypeBytes();

  /**
   * <code>string explanation_method = 2;</code>
   */
  java.lang.String getExplanationMethod();
  /**
   * <code>string explanation_method = 2;</code>
   */
  com.google.protobuf.ByteString
      getExplanationMethodBytes();

  /**
   * <code>string explainability_model = 3;</code>
   */
  java.lang.String getExplainabilityModel();
  /**
   * <code>string explainability_model = 3;</code>
   */
  com.google.protobuf.ByteString
      getExplainabilityModelBytes();

  /**
   * <code>string plot_name = 4;</code>
   */
  java.lang.String getPlotName();
  /**
   * <code>string plot_name = 4;</code>
   */
  com.google.protobuf.ByteString
      getPlotNameBytes();

  /**
   * <code>string plot_descr = 5;</code>
   */
  java.lang.String getPlotDescr();
  /**
   * <code>string plot_descr = 5;</code>
   */
  com.google.protobuf.ByteString
      getPlotDescrBytes();

  /**
   * <code>string plot_type = 6;</code>
   */
  java.lang.String getPlotType();
  /**
   * <code>string plot_type = 6;</code>
   */
  com.google.protobuf.ByteString
      getPlotTypeBytes();

  /**
   * <code>.Features features = 7;</code>
   */
  boolean hasFeatures();
  /**
   * <code>.Features features = 7;</code>
   */
  gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Features getFeatures();
  /**
   * <code>.Features features = 7;</code>
   */
  gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.FeaturesOrBuilder getFeaturesOrBuilder();

  /**
   * <code>.Axis xAxis = 8;</code>
   */
  boolean hasXAxis();
  /**
   * <code>.Axis xAxis = 8;</code>
   */
  gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis getXAxis();
  /**
   * <code>.Axis xAxis = 8;</code>
   */
  gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.AxisOrBuilder getXAxisOrBuilder();

  /**
   * <code>.Axis yAxis = 9;</code>
   */
  boolean hasYAxis();
  /**
   * <code>.Axis yAxis = 9;</code>
   */
  gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis getYAxis();
  /**
   * <code>.Axis yAxis = 9;</code>
   */
  gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.AxisOrBuilder getYAxisOrBuilder();

  /**
   * <code>.Axis zAxis = 10;</code>
   */
  boolean hasZAxis();
  /**
   * <code>.Axis zAxis = 10;</code>
   */
  gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Axis getZAxis();
  /**
   * <code>.Axis zAxis = 10;</code>
   */
  gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.AxisOrBuilder getZAxisOrBuilder();

  /**
   * <code>map&lt;string, .TableContents&gt; table_contents = 11;</code>
   */
  int getTableContentsCount();
  /**
   * <code>map&lt;string, .TableContents&gt; table_contents = 11;</code>
   */
  boolean containsTableContents(
      java.lang.String key);
  /**
   * Use {@link #getTableContentsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.TableContents>
  getTableContents();
  /**
   * <code>map&lt;string, .TableContents&gt; table_contents = 11;</code>
   */
  java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.TableContents>
  getTableContentsMap();
  /**
   * <code>map&lt;string, .TableContents&gt; table_contents = 11;</code>
   */

  gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.TableContents getTableContentsOrDefault(
      java.lang.String key,
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.TableContents defaultValue);
  /**
   * <code>map&lt;string, .TableContents&gt; table_contents = 11;</code>
   */

  gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.TableContents getTableContentsOrThrow(
      java.lang.String key);
}
