// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xai_service.proto

package gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated;

public interface ExplanationsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ExplanationsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Fields specific to ComputePDP explanation
   * </pre>
   *
   * <code>string pdp_hp_values = 1;</code>
   */
  java.lang.String getPdpHpValues();
  /**
   * <pre>
   * Fields specific to ComputePDP explanation
   * </pre>
   *
   * <code>string pdp_hp_values = 1;</code>
   */
  com.google.protobuf.ByteString
      getPdpHpValuesBytes();

  /**
   * <code>string pdp_values = 2;</code>
   */
  java.lang.String getPdpValues();
  /**
   * <code>string pdp_values = 2;</code>
   */
  com.google.protobuf.ByteString
      getPdpValuesBytes();

  /**
   * <pre>
   * Fields specific to ComputePDP2D explanation
   * </pre>
   *
   * <code>string pdp2d_xi = 3;</code>
   */
  java.lang.String getPdp2DXi();
  /**
   * <pre>
   * Fields specific to ComputePDP2D explanation
   * </pre>
   *
   * <code>string pdp2d_xi = 3;</code>
   */
  com.google.protobuf.ByteString
      getPdp2DXiBytes();

  /**
   * <code>string pdp2d_yi = 4;</code>
   */
  java.lang.String getPdp2DYi();
  /**
   * <code>string pdp2d_yi = 4;</code>
   */
  com.google.protobuf.ByteString
      getPdp2DYiBytes();

  /**
   * <code>string pdp2d_zi = 5;</code>
   */
  java.lang.String getPdp2DZi();
  /**
   * <code>string pdp2d_zi = 5;</code>
   */
  com.google.protobuf.ByteString
      getPdp2DZiBytes();

  /**
   * <pre>
   * Fields specific to ComputeALE explanation
   * </pre>
   *
   * <code>string ale_data = 6;</code>
   */
  java.lang.String getAleData();
  /**
   * <pre>
   * Fields specific to ComputeALE explanation
   * </pre>
   *
   * <code>string ale_data = 6;</code>
   */
  com.google.protobuf.ByteString
      getAleDataBytes();

  /**
   * <pre>
   * Fields specific to InfluenceFunction explanation
   * </pre>
   *
   * <code>repeated float influences = 7;</code>
   */
  java.util.List<java.lang.Float> getInfluencesList();
  /**
   * <pre>
   * Fields specific to InfluenceFunction explanation
   * </pre>
   *
   * <code>repeated float influences = 7;</code>
   */
  int getInfluencesCount();
  /**
   * <pre>
   * Fields specific to InfluenceFunction explanation
   * </pre>
   *
   * <code>repeated float influences = 7;</code>
   */
  float getInfluences(int index);

  /**
   * <code>bytes positive = 8;</code>
   */
  com.google.protobuf.ByteString getPositive();

  /**
   * <code>bytes negative = 9;</code>
   */
  com.google.protobuf.ByteString getNegative();

  /**
   * <pre>
   * Fields specific to Counterfactual Explanations
   * </pre>
   *
   * <code>bytes cfs = 10;</code>
   */
  com.google.protobuf.ByteString getCfs();

  /**
   * <pre>
   *------------------ Model Explainability --------------------------------------------------
   * ------------ PDP Fields -------------------------
   * </pre>
   *
   * <code>string pdp_vals = 11;</code>
   */
  java.lang.String getPdpVals();
  /**
   * <pre>
   *------------------ Model Explainability --------------------------------------------------
   * ------------ PDP Fields -------------------------
   * </pre>
   *
   * <code>string pdp_vals = 11;</code>
   */
  com.google.protobuf.ByteString
      getPdpValsBytes();

  /**
   * <code>string pdp_effect = 12;</code>
   */
  java.lang.String getPdpEffect();
  /**
   * <code>string pdp_effect = 12;</code>
   */
  com.google.protobuf.ByteString
      getPdpEffectBytes();
}
