// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xai_service.proto

package gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated;

public interface Feature_ExplanationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Feature_Explanation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string feature_names = 1;</code>
   */
  java.util.List<java.lang.String>
      getFeatureNamesList();
  /**
   * <code>repeated string feature_names = 1;</code>
   */
  int getFeatureNamesCount();
  /**
   * <code>repeated string feature_names = 1;</code>
   */
  java.lang.String getFeatureNames(int index);
  /**
   * <code>repeated string feature_names = 1;</code>
   */
  com.google.protobuf.ByteString
      getFeatureNamesBytes(int index);

  /**
   * <code>map&lt;string, .ExplanationsResponse&gt; plots = 2;</code>
   */
  int getPlotsCount();
  /**
   * <code>map&lt;string, .ExplanationsResponse&gt; plots = 2;</code>
   */
  boolean containsPlots(
      java.lang.String key);
  /**
   * Use {@link #getPlotsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse>
  getPlots();
  /**
   * <code>map&lt;string, .ExplanationsResponse&gt; plots = 2;</code>
   */
  java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse>
  getPlotsMap();
  /**
   * <code>map&lt;string, .ExplanationsResponse&gt; plots = 2;</code>
   */

  gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse getPlotsOrDefault(
      java.lang.String key,
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse defaultValue);
  /**
   * <code>map&lt;string, .ExplanationsResponse&gt; plots = 2;</code>
   */

  gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse getPlotsOrThrow(
      java.lang.String key);

  /**
   * <code>map&lt;string, .ExplanationsResponse&gt; tables = 3;</code>
   */
  int getTablesCount();
  /**
   * <code>map&lt;string, .ExplanationsResponse&gt; tables = 3;</code>
   */
  boolean containsTables(
      java.lang.String key);
  /**
   * Use {@link #getTablesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse>
  getTables();
  /**
   * <code>map&lt;string, .ExplanationsResponse&gt; tables = 3;</code>
   */
  java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse>
  getTablesMap();
  /**
   * <code>map&lt;string, .ExplanationsResponse&gt; tables = 3;</code>
   */

  gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse getTablesOrDefault(
      java.lang.String key,
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse defaultValue);
  /**
   * <code>map&lt;string, .ExplanationsResponse&gt; tables = 3;</code>
   */

  gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse getTablesOrThrow(
      java.lang.String key);
}
