// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xai_service.proto

package gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated;

/**
 * Protobuf type {@code Feature_Explanation}
 */
public  final class Feature_Explanation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Feature_Explanation)
    Feature_ExplanationOrBuilder {
  // Use Feature_Explanation.newBuilder() to construct.
  private Feature_Explanation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Feature_Explanation() {
    featureNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Feature_Explanation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              featureNames_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            featureNames_.add(s);
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              plots_ = com.google.protobuf.MapField.newMapField(
                  PlotsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse>
            plots__ = input.readMessage(
                PlotsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            plots_.getMutableMap().put(
                plots__.getKey(), plots__.getValue());
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              tables_ = com.google.protobuf.MapField.newMapField(
                  TablesDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000004;
            }
            com.google.protobuf.MapEntry<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse>
            tables__ = input.readMessage(
                TablesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            tables_.getMutableMap().put(
                tables__.getKey(), tables__.getValue());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        featureNames_ = featureNames_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_Feature_Explanation_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 2:
        return internalGetPlots();
      case 3:
        return internalGetTables();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_Feature_Explanation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation.class, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation.Builder.class);
  }

  public static final int FEATURE_NAMES_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList featureNames_;
  /**
   * <code>repeated string feature_names = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getFeatureNamesList() {
    return featureNames_;
  }
  /**
   * <code>repeated string feature_names = 1;</code>
   */
  public int getFeatureNamesCount() {
    return featureNames_.size();
  }
  /**
   * <code>repeated string feature_names = 1;</code>
   */
  public java.lang.String getFeatureNames(int index) {
    return featureNames_.get(index);
  }
  /**
   * <code>repeated string feature_names = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFeatureNamesBytes(int index) {
    return featureNames_.getByteString(index);
  }

  public static final int PLOTS_FIELD_NUMBER = 2;
  private static final class PlotsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse>newDefaultInstance(
                gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_Feature_Explanation_PlotsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> plots_;
  private com.google.protobuf.MapField<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse>
  internalGetPlots() {
    if (plots_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          PlotsDefaultEntryHolder.defaultEntry);
    }
    return plots_;
  }

  public int getPlotsCount() {
    return internalGetPlots().getMap().size();
  }
  /**
   * <code>map&lt;string, .ExplanationsResponse&gt; plots = 2;</code>
   */

  public boolean containsPlots(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetPlots().getMap().containsKey(key);
  }
  /**
   * Use {@link #getPlotsMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> getPlots() {
    return getPlotsMap();
  }
  /**
   * <code>map&lt;string, .ExplanationsResponse&gt; plots = 2;</code>
   */

  public java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> getPlotsMap() {
    return internalGetPlots().getMap();
  }
  /**
   * <code>map&lt;string, .ExplanationsResponse&gt; plots = 2;</code>
   */

  public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse getPlotsOrDefault(
      java.lang.String key,
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> map =
        internalGetPlots().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .ExplanationsResponse&gt; plots = 2;</code>
   */

  public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse getPlotsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> map =
        internalGetPlots().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int TABLES_FIELD_NUMBER = 3;
  private static final class TablesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse>newDefaultInstance(
                gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_Feature_Explanation_TablesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> tables_;
  private com.google.protobuf.MapField<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse>
  internalGetTables() {
    if (tables_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          TablesDefaultEntryHolder.defaultEntry);
    }
    return tables_;
  }

  public int getTablesCount() {
    return internalGetTables().getMap().size();
  }
  /**
   * <code>map&lt;string, .ExplanationsResponse&gt; tables = 3;</code>
   */

  public boolean containsTables(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetTables().getMap().containsKey(key);
  }
  /**
   * Use {@link #getTablesMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> getTables() {
    return getTablesMap();
  }
  /**
   * <code>map&lt;string, .ExplanationsResponse&gt; tables = 3;</code>
   */

  public java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> getTablesMap() {
    return internalGetTables().getMap();
  }
  /**
   * <code>map&lt;string, .ExplanationsResponse&gt; tables = 3;</code>
   */

  public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse getTablesOrDefault(
      java.lang.String key,
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> map =
        internalGetTables().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .ExplanationsResponse&gt; tables = 3;</code>
   */

  public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse getTablesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> map =
        internalGetTables().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < featureNames_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, featureNames_.getRaw(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetPlots(),
        PlotsDefaultEntryHolder.defaultEntry,
        2);
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetTables(),
        TablesDefaultEntryHolder.defaultEntry,
        3);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < featureNames_.size(); i++) {
        dataSize += computeStringSizeNoTag(featureNames_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFeatureNamesList().size();
    }
    for (java.util.Map.Entry<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> entry
         : internalGetPlots().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse>
      plots__ = PlotsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, plots__);
    }
    for (java.util.Map.Entry<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> entry
         : internalGetTables().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse>
      tables__ = TablesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, tables__);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation)) {
      return super.equals(obj);
    }
    gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation other = (gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation) obj;

    boolean result = true;
    result = result && getFeatureNamesList()
        .equals(other.getFeatureNamesList());
    result = result && internalGetPlots().equals(
        other.internalGetPlots());
    result = result && internalGetTables().equals(
        other.internalGetTables());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getFeatureNamesCount() > 0) {
      hash = (37 * hash) + FEATURE_NAMES_FIELD_NUMBER;
      hash = (53 * hash) + getFeatureNamesList().hashCode();
    }
    if (!internalGetPlots().getMap().isEmpty()) {
      hash = (37 * hash) + PLOTS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetPlots().hashCode();
    }
    if (!internalGetTables().getMap().isEmpty()) {
      hash = (37 * hash) + TABLES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetTables().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Feature_Explanation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Feature_Explanation)
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_ExplanationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_Feature_Explanation_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetPlots();
        case 3:
          return internalGetTables();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutablePlots();
        case 3:
          return internalGetMutableTables();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_Feature_Explanation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation.class, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation.Builder.class);
    }

    // Construct using gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      featureNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutablePlots().clear();
      internalGetMutableTables().clear();
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_Feature_Explanation_descriptor;
    }

    public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation getDefaultInstanceForType() {
      return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation.getDefaultInstance();
    }

    public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation build() {
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation buildPartial() {
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation result = new gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        featureNames_ = featureNames_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.featureNames_ = featureNames_;
      result.plots_ = internalGetPlots();
      result.plots_.makeImmutable();
      result.tables_ = internalGetTables();
      result.tables_.makeImmutable();
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation) {
        return mergeFrom((gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation other) {
      if (other == gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation.getDefaultInstance()) return this;
      if (!other.featureNames_.isEmpty()) {
        if (featureNames_.isEmpty()) {
          featureNames_ = other.featureNames_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureFeatureNamesIsMutable();
          featureNames_.addAll(other.featureNames_);
        }
        onChanged();
      }
      internalGetMutablePlots().mergeFrom(
          other.internalGetPlots());
      internalGetMutableTables().mergeFrom(
          other.internalGetTables());
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList featureNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureFeatureNamesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        featureNames_ = new com.google.protobuf.LazyStringArrayList(featureNames_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string feature_names = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFeatureNamesList() {
      return featureNames_.getUnmodifiableView();
    }
    /**
     * <code>repeated string feature_names = 1;</code>
     */
    public int getFeatureNamesCount() {
      return featureNames_.size();
    }
    /**
     * <code>repeated string feature_names = 1;</code>
     */
    public java.lang.String getFeatureNames(int index) {
      return featureNames_.get(index);
    }
    /**
     * <code>repeated string feature_names = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFeatureNamesBytes(int index) {
      return featureNames_.getByteString(index);
    }
    /**
     * <code>repeated string feature_names = 1;</code>
     */
    public Builder setFeatureNames(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFeatureNamesIsMutable();
      featureNames_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string feature_names = 1;</code>
     */
    public Builder addFeatureNames(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFeatureNamesIsMutable();
      featureNames_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string feature_names = 1;</code>
     */
    public Builder addAllFeatureNames(
        java.lang.Iterable<java.lang.String> values) {
      ensureFeatureNamesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, featureNames_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string feature_names = 1;</code>
     */
    public Builder clearFeatureNames() {
      featureNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string feature_names = 1;</code>
     */
    public Builder addFeatureNamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureFeatureNamesIsMutable();
      featureNames_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> plots_;
    private com.google.protobuf.MapField<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse>
    internalGetPlots() {
      if (plots_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PlotsDefaultEntryHolder.defaultEntry);
      }
      return plots_;
    }
    private com.google.protobuf.MapField<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse>
    internalGetMutablePlots() {
      onChanged();;
      if (plots_ == null) {
        plots_ = com.google.protobuf.MapField.newMapField(
            PlotsDefaultEntryHolder.defaultEntry);
      }
      if (!plots_.isMutable()) {
        plots_ = plots_.copy();
      }
      return plots_;
    }

    public int getPlotsCount() {
      return internalGetPlots().getMap().size();
    }
    /**
     * <code>map&lt;string, .ExplanationsResponse&gt; plots = 2;</code>
     */

    public boolean containsPlots(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetPlots().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPlotsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> getPlots() {
      return getPlotsMap();
    }
    /**
     * <code>map&lt;string, .ExplanationsResponse&gt; plots = 2;</code>
     */

    public java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> getPlotsMap() {
      return internalGetPlots().getMap();
    }
    /**
     * <code>map&lt;string, .ExplanationsResponse&gt; plots = 2;</code>
     */

    public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse getPlotsOrDefault(
        java.lang.String key,
        gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> map =
          internalGetPlots().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .ExplanationsResponse&gt; plots = 2;</code>
     */

    public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse getPlotsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> map =
          internalGetPlots().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearPlots() {
      internalGetMutablePlots().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .ExplanationsResponse&gt; plots = 2;</code>
     */

    public Builder removePlots(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutablePlots().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse>
    getMutablePlots() {
      return internalGetMutablePlots().getMutableMap();
    }
    /**
     * <code>map&lt;string, .ExplanationsResponse&gt; plots = 2;</code>
     */
    public Builder putPlots(
        java.lang.String key,
        gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutablePlots().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .ExplanationsResponse&gt; plots = 2;</code>
     */

    public Builder putAllPlots(
        java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> values) {
      internalGetMutablePlots().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> tables_;
    private com.google.protobuf.MapField<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse>
    internalGetTables() {
      if (tables_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TablesDefaultEntryHolder.defaultEntry);
      }
      return tables_;
    }
    private com.google.protobuf.MapField<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse>
    internalGetMutableTables() {
      onChanged();;
      if (tables_ == null) {
        tables_ = com.google.protobuf.MapField.newMapField(
            TablesDefaultEntryHolder.defaultEntry);
      }
      if (!tables_.isMutable()) {
        tables_ = tables_.copy();
      }
      return tables_;
    }

    public int getTablesCount() {
      return internalGetTables().getMap().size();
    }
    /**
     * <code>map&lt;string, .ExplanationsResponse&gt; tables = 3;</code>
     */

    public boolean containsTables(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetTables().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTablesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> getTables() {
      return getTablesMap();
    }
    /**
     * <code>map&lt;string, .ExplanationsResponse&gt; tables = 3;</code>
     */

    public java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> getTablesMap() {
      return internalGetTables().getMap();
    }
    /**
     * <code>map&lt;string, .ExplanationsResponse&gt; tables = 3;</code>
     */

    public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse getTablesOrDefault(
        java.lang.String key,
        gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> map =
          internalGetTables().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .ExplanationsResponse&gt; tables = 3;</code>
     */

    public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse getTablesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> map =
          internalGetTables().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearTables() {
      internalGetMutableTables().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .ExplanationsResponse&gt; tables = 3;</code>
     */

    public Builder removeTables(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableTables().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse>
    getMutableTables() {
      return internalGetMutableTables().getMutableMap();
    }
    /**
     * <code>map&lt;string, .ExplanationsResponse&gt; tables = 3;</code>
     */
    public Builder putTables(
        java.lang.String key,
        gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableTables().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .ExplanationsResponse&gt; tables = 3;</code>
     */

    public Builder putAllTables(
        java.util.Map<java.lang.String, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ExplanationsResponse> values) {
      internalGetMutableTables().getMutableMap()
          .putAll(values);
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:Feature_Explanation)
  }

  // @@protoc_insertion_point(class_scope:Feature_Explanation)
  private static final gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation();
  }

  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Feature_Explanation>
      PARSER = new com.google.protobuf.AbstractParser<Feature_Explanation>() {
    public Feature_Explanation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Feature_Explanation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Feature_Explanation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Feature_Explanation> getParserForType() {
    return PARSER;
  }

  public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

