// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xai_service.proto

package gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated;

public interface InitializationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InitializationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string model_name = 1;</code>
   */
  java.lang.String getModelName();
  /**
   * <code>string model_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getModelNameBytes();
}
