// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xai_service.proto

package gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated;

/**
 * Protobuf type {@code ModelAnalysisTaskResponse}
 */
public  final class ModelAnalysisTaskResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ModelAnalysisTaskResponse)
    ModelAnalysisTaskResponseOrBuilder {
  // Use ModelAnalysisTaskResponse.newBuilder() to construct.
  private ModelAnalysisTaskResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ModelAnalysisTaskResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ModelAnalysisTaskResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation.Builder subBuilder = null;
            if (featureExplanation_ != null) {
              subBuilder = featureExplanation_.toBuilder();
            }
            featureExplanation_ = input.readMessage(gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(featureExplanation_);
              featureExplanation_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_ModelAnalysisTaskResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_ModelAnalysisTaskResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse.class, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse.Builder.class);
  }

  public static final int FEATURE_EXPLANATION_FIELD_NUMBER = 1;
  private gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation featureExplanation_;
  /**
   * <code>.Feature_Explanation feature_explanation = 1;</code>
   */
  public boolean hasFeatureExplanation() {
    return featureExplanation_ != null;
  }
  /**
   * <code>.Feature_Explanation feature_explanation = 1;</code>
   */
  public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation getFeatureExplanation() {
    return featureExplanation_ == null ? gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation.getDefaultInstance() : featureExplanation_;
  }
  /**
   * <code>.Feature_Explanation feature_explanation = 1;</code>
   */
  public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_ExplanationOrBuilder getFeatureExplanationOrBuilder() {
    return getFeatureExplanation();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (featureExplanation_ != null) {
      output.writeMessage(1, getFeatureExplanation());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (featureExplanation_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getFeatureExplanation());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse)) {
      return super.equals(obj);
    }
    gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse other = (gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse) obj;

    boolean result = true;
    result = result && (hasFeatureExplanation() == other.hasFeatureExplanation());
    if (hasFeatureExplanation()) {
      result = result && getFeatureExplanation()
          .equals(other.getFeatureExplanation());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasFeatureExplanation()) {
      hash = (37 * hash) + FEATURE_EXPLANATION_FIELD_NUMBER;
      hash = (53 * hash) + getFeatureExplanation().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ModelAnalysisTaskResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ModelAnalysisTaskResponse)
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_ModelAnalysisTaskResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_ModelAnalysisTaskResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse.class, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse.Builder.class);
    }

    // Construct using gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (featureExplanationBuilder_ == null) {
        featureExplanation_ = null;
      } else {
        featureExplanation_ = null;
        featureExplanationBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.GrpcProto.internal_static_ModelAnalysisTaskResponse_descriptor;
    }

    public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse getDefaultInstanceForType() {
      return gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse.getDefaultInstance();
    }

    public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse build() {
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse buildPartial() {
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse result = new gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse(this);
      if (featureExplanationBuilder_ == null) {
        result.featureExplanation_ = featureExplanation_;
      } else {
        result.featureExplanation_ = featureExplanationBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse) {
        return mergeFrom((gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse other) {
      if (other == gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse.getDefaultInstance()) return this;
      if (other.hasFeatureExplanation()) {
        mergeFeatureExplanation(other.getFeatureExplanation());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation featureExplanation_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation.Builder, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_ExplanationOrBuilder> featureExplanationBuilder_;
    /**
     * <code>.Feature_Explanation feature_explanation = 1;</code>
     */
    public boolean hasFeatureExplanation() {
      return featureExplanationBuilder_ != null || featureExplanation_ != null;
    }
    /**
     * <code>.Feature_Explanation feature_explanation = 1;</code>
     */
    public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation getFeatureExplanation() {
      if (featureExplanationBuilder_ == null) {
        return featureExplanation_ == null ? gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation.getDefaultInstance() : featureExplanation_;
      } else {
        return featureExplanationBuilder_.getMessage();
      }
    }
    /**
     * <code>.Feature_Explanation feature_explanation = 1;</code>
     */
    public Builder setFeatureExplanation(gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation value) {
      if (featureExplanationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        featureExplanation_ = value;
        onChanged();
      } else {
        featureExplanationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Feature_Explanation feature_explanation = 1;</code>
     */
    public Builder setFeatureExplanation(
        gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation.Builder builderForValue) {
      if (featureExplanationBuilder_ == null) {
        featureExplanation_ = builderForValue.build();
        onChanged();
      } else {
        featureExplanationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Feature_Explanation feature_explanation = 1;</code>
     */
    public Builder mergeFeatureExplanation(gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation value) {
      if (featureExplanationBuilder_ == null) {
        if (featureExplanation_ != null) {
          featureExplanation_ =
            gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation.newBuilder(featureExplanation_).mergeFrom(value).buildPartial();
        } else {
          featureExplanation_ = value;
        }
        onChanged();
      } else {
        featureExplanationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Feature_Explanation feature_explanation = 1;</code>
     */
    public Builder clearFeatureExplanation() {
      if (featureExplanationBuilder_ == null) {
        featureExplanation_ = null;
        onChanged();
      } else {
        featureExplanation_ = null;
        featureExplanationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Feature_Explanation feature_explanation = 1;</code>
     */
    public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation.Builder getFeatureExplanationBuilder() {
      
      onChanged();
      return getFeatureExplanationFieldBuilder().getBuilder();
    }
    /**
     * <code>.Feature_Explanation feature_explanation = 1;</code>
     */
    public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_ExplanationOrBuilder getFeatureExplanationOrBuilder() {
      if (featureExplanationBuilder_ != null) {
        return featureExplanationBuilder_.getMessageOrBuilder();
      } else {
        return featureExplanation_ == null ?
            gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation.getDefaultInstance() : featureExplanation_;
      }
    }
    /**
     * <code>.Feature_Explanation feature_explanation = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation.Builder, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_ExplanationOrBuilder> 
        getFeatureExplanationFieldBuilder() {
      if (featureExplanationBuilder_ == null) {
        featureExplanationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation.Builder, gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_ExplanationOrBuilder>(
                getFeatureExplanation(),
                getParentForChildren(),
                isClean());
        featureExplanation_ = null;
      }
      return featureExplanationBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:ModelAnalysisTaskResponse)
  }

  // @@protoc_insertion_point(class_scope:ModelAnalysisTaskResponse)
  private static final gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse();
  }

  public static gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ModelAnalysisTaskResponse>
      PARSER = new com.google.protobuf.AbstractParser<ModelAnalysisTaskResponse>() {
    public ModelAnalysisTaskResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ModelAnalysisTaskResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ModelAnalysisTaskResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ModelAnalysisTaskResponse> getParserForType() {
    return PARSER;
  }

  public gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.ModelAnalysisTaskResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

