// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xai_service.proto

package gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated;

public interface ModelAnalysisTaskResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ModelAnalysisTaskResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Feature_Explanation feature_explanation = 1;</code>
   */
  boolean hasFeatureExplanation();
  /**
   * <code>.Feature_Explanation feature_explanation = 1;</code>
   */
  gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_Explanation getFeatureExplanation();
  /**
   * <code>.Feature_Explanation feature_explanation = 1;</code>
   */
  gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated.Feature_ExplanationOrBuilder getFeatureExplanationOrBuilder();
}
