// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xai_service.proto

package gr.imsi.athenarc.xtremexpvisapi.domain.GrpcAutoGenerated;

public interface TableContentsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TableContents)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string values = 1;</code>
   */
  java.util.List<java.lang.String>
      getValuesList();
  /**
   * <code>repeated string values = 1;</code>
   */
  int getValuesCount();
  /**
   * <code>repeated string values = 1;</code>
   */
  java.lang.String getValues(int index);
  /**
   * <code>repeated string values = 1;</code>
   */
  com.google.protobuf.ByteString
      getValuesBytes(int index);
}
